import { InfluencerItem } from "./types";

export const INFLUENCERS_DATA: InfluencerItem[] = [
  {
    id: "aboflah",
    slug: "aboflah",
    name: "Abo Flah",
    nationality: "Kuwait",
    flag: "🇰🇼",
    totalFollowers: "70M",
    rawFollowers: 70,
    role: "Gaming & Humanitarian Creator",
    instagram: "aboflah",
    youtube: "AboFlah",
    tiktok: "aboflah",
    bio: "One of the most celebrated digital creators in the Arab world, known for record-breaking charity livestreams and viral entertainment.",
    collaborations: ["Global Charity Livestream Marathon", "World's Coolest Winter Campaign", "Turnkey Studio Production"],
    signatureProductions: ["12-Hour Continuous Multi-Cam Stream", "Custom Gaming Soundstage Rig", "AI Highlight Syndication"],
    demographics: {
      topCountries: [
        { country: "Saudi Arabia", flag: "🇸🇦", percentage: 44 },
        { country: "UAE", flag: "🇦🇪", percentage: 22 },
        { country: "Egypt", flag: "🇪🇬", percentage: 16 },
        { country: "Kuwait", flag: "🇰🇼", percentage: 12 },
      ],
      primaryAgeGroup: "16–32 (82%)",
      genderSplit: { male: 68, female: 32 },
      monthlyImpressions: "120M+",
      engagementRate: "8.2%",
    },
    avatar: "/images/influencers/aboflah.jpg",
  },
  {
    id: "abir-saghir",
    slug: "abir-saghir",
    name: "Abir El Saghir",
    nationality: "Lebanon",
    flag: "🇱🇧",
    totalFollowers: "72M",
    rawFollowers: 72,
    role: "Culinary & Lifestyle Creator",
    instagram: "abiresag",
    youtube: "abirsaghir",
    tiktok: "abir.sag",
    bio: "Global culinary sensation sharing traditional Arab and world cuisine with cinematic visual flair.",
    collaborations: ["Taste of the Emirates Series", "Traditional Heritage Cooking Special", "Macro Gourmet Lighting"],
    signatureProductions: ["4K Overhead Food Stage Rig", "Slow-Motion High-Speed Optics", "Bespoke Acoustic Foley Mixing"],
    demographics: {
      topCountries: [
        { country: "UAE", flag: "🇦🇪", percentage: 32 },
        { country: "Saudi Arabia", flag: "🇸🇦", percentage: 28 },
        { country: "USA & Europe", flag: "🌍", percentage: 24 },
        { country: "Lebanon", flag: "🇱🇧", percentage: 12 },
      ],
      primaryAgeGroup: "20–42 (75%)",
      genderSplit: { male: 38, female: 62 },
      monthlyImpressions: "140M+",
      engagementRate: "9.1%",
    },
    avatar: "/images/influencers/abir-saghir.jpg",
  },
  {
    id: "noor-stars",
    slug: "noor-stars",
    name: "Noor Stars",
    nationality: "Iraq",
    flag: "🇮🇶",
    totalFollowers: "62M",
    rawFollowers: 62,
    role: "Beauty, Lifestyle & Music Artist",
    instagram: "noorstars",
    youtube: "noorstars",
    tiktok: "noorstars",
    bio: "The Arab world's premier beauty and lifestyle trailblazer, musician, and podcast host.",
    collaborations: ["Music Video Studio Shoots", "Podcast Suite Season Ingest", "Fashion Week Coverage"],
    signatureProductions: ["Full-Scale Studio A Music Video", "Podcast Suite Multi-Mic Switching", "HDR Glamour Lighting Grid"],
    demographics: {
      topCountries: [
        { country: "Saudi Arabia", flag: "🇸🇦", percentage: 40 },
        { country: "Iraq", flag: "🇮🇶", percentage: 26 },
        { country: "UAE", flag: "🇦🇪", percentage: 20 },
        { country: "Jordan", flag: "🇯🇴", percentage: 10 },
      ],
      primaryAgeGroup: "18–35 (79%)",
      genderSplit: { male: 25, female: 75 },
      monthlyImpressions: "95M+",
      engagementRate: "7.4%",
    },
    avatar: "/images/influencers/noor-stars.jpg",
  },
  {
    id: "narins-beauty",
    slug: "narins-beauty",
    name: "Narins Beauty",
    nationality: "Syria-Kurd",
    flag: "🇸🇾",
    totalFollowers: "50M",
    rawFollowers: 50,
    role: "Lifestyle & Music Creator",
    instagram: "narins_beauty",
    youtube: "Narobeauty",
    tiktok: "narins.beauty_",
    bio: "Vlogger and music artist producing high-end lifestyle vlogs, fashion reveals, and chart-topping singles.",
    collaborations: ["Music Single Release Visuals", "Lifestyle Series Production", "Studio Cyclorama Shoots"],
    signatureProductions: ["Infinite White Cyc Fashion Sequences", "Anamorphic Music Video Set", "Turnkey Color Grading"],
    demographics: {
      topCountries: [
        { country: "Saudi Arabia", flag: "🇸🇦", percentage: 38 },
        { country: "UAE", flag: "🇦🇪", percentage: 24 },
        { country: "Germany / Europe", flag: "🇪🇺", percentage: 22 },
        { country: "Syria / Levant", flag: "🇸🇾", percentage: 14 },
      ],
      primaryAgeGroup: "16–30 (84%)",
      genderSplit: { male: 30, female: 70 },
      monthlyImpressions: "75M+",
      engagementRate: "6.8%",
    },
    avatar: "/images/influencers/narins-beauty.jpg",
  },
  {
    id: "asala-almaleh",
    slug: "asala-almaleh",
    name: "Asala Almaleh",
    nationality: "Syria-USA",
    flag: "🇸🇾",
    totalFollowers: "43.5M",
    rawFollowers: 43.5,
    role: "Family & Entertainment Star",
    instagram: "asala",
    youtube: "TheAnazalaFamily",
    tiktok: "heyitsasala",
    bio: "Co-creator of the viral Anasala family, creating wholesome entertainment, challenges, and reality content.",
    collaborations: ["Family Reality Special", "Holiday Season Production", "Brand Crossover Formats"],
    signatureProductions: ["Mobile Outdoor Broadcast Crew", "Multi-Room Wireless Audio", "Same-Day Ingest & Edit"],
    demographics: {
      topCountries: [
        { country: "Saudi Arabia", flag: "🇸🇦", percentage: 46 },
        { country: "UAE", flag: "🇦🇪", percentage: 25 },
        { country: "USA & Canada", flag: "🇺🇸", percentage: 18 },
        { country: "Egypt", flag: "🇪🇬", percentage: 11 },
      ],
      primaryAgeGroup: "18–45 (72%)",
      genderSplit: { male: 42, female: 58 },
      monthlyImpressions: "65M+",
      engagementRate: "8.0%",
    },
    avatar: "/images/influencers/asala-almaleh.jpg",
  },
  {
    id: "osama-marwah",
    slug: "osama-marwah",
    name: "Osama Marwah",
    nationality: "Syria",
    flag: "🇸🇾",
    totalFollowers: "33M",
    rawFollowers: 33,
    role: "Comedy & Lifestyle Creator",
    instagram: "ossymarwah",
    youtube: "ossymarwah",
    tiktok: "ossymarwah",
    bio: "Entertainer and digital creator famous for comedy formats, travel vlogs, and interactive influencer crossovers.",
    collaborations: ["Creator Crossover Challenges", "Comedy Special Series", "Digital Talk Formats"],
    signatureProductions: ["Studio B Comedy Podcast Ingest", "Multi-Angle Reaction Cams", "Dynamic Fast-Cut Editing"],
    demographics: {
      topCountries: [
        { country: "Saudi Arabia", flag: "🇸🇦", percentage: 42 },
        { country: "UAE", flag: "🇦🇪", percentage: 28 },
        { country: "Egypt", flag: "🇪🇬", percentage: 18 },
        { country: "Levant", flag: "🌍", percentage: 12 },
      ],
      primaryAgeGroup: "16–30 (80%)",
      genderSplit: { male: 56, female: 44 },
      monthlyImpressions: "50M+",
      engagementRate: "7.1%",
    },
    avatar: "/images/influencers/osama-marwah.jpg",
  },
  {
    id: "mohamad-adnan",
    slug: "mohamad-adnan",
    name: "Mohamad Adnan",
    nationality: "Jordan",
    flag: "🇯🇴",
    totalFollowers: "28M",
    rawFollowers: 28,
    role: "Sports Analyst & Entertainment",
    instagram: "mohdadnan23",
    youtube: "mohamadadnan",
    tiktok: "mohdadnan23",
    bio: "The Arab region's leading football content creator, sports analyst, and live tournament host.",
    collaborations: ["World Tournament Live Analysis", "Stadium On-Location Show", "Exclusive Player Interviews"],
    signatureProductions: ["OB-VAN Stadium Live Ingest", "Sports Studio Holographic Graphics", "Ultra-Low Latency Streaming"],
    demographics: {
      topCountries: [
        { country: "Saudi Arabia", flag: "🇸🇦", percentage: 38 },
        { country: "Jordan & Palestine", flag: "🇯🇴", percentage: 24 },
        { country: "UAE & Qatar", flag: "🇦🇪", percentage: 22 },
        { country: "Egypt", flag: "🇪🇬", percentage: 16 },
      ],
      primaryAgeGroup: "16–38 (88%)",
      genderSplit: { male: 82, female: 18 },
      monthlyImpressions: "45M+",
      engagementRate: "8.5%",
    },
    avatar: "/images/influencers/mohamad-adnan.jpg",
  },
  {
    id: "ghaith-marwan",
    slug: "ghaith-marwan",
    name: "Ghaith Marwan",
    nationality: "Syria",
    flag: "🇸🇾",
    totalFollowers: "28M",
    rawFollowers: 28,
    role: "Vlogs & Digital Shows",
    instagram: "ghaith_marwan",
    youtube: "Ghaithmarwan",
    tiktok: "ghaith_marwan",
    bio: "Charismatic vlogger and show host creating dynamic lifestyle content and digital series.",
    collaborations: ["Vlog Series Master Edition", "Celebrity Challenge Episode", "Seasonal Specials"],
    signatureProductions: ["Cinematic Field Audio Rig", "4K Run-and-Gun Cinema Package", "AI Color Consistency Engine"],
    demographics: {
      topCountries: [
        { country: "Saudi Arabia", flag: "🇸🇦", percentage: 40 },
        { country: "UAE", flag: "🇦🇪", percentage: 26 },
        { country: "Syria", flag: "🇸🇾", percentage: 18 },
        { country: "Levant", flag: "🌍", percentage: 16 },
      ],
      primaryAgeGroup: "16–32 (81%)",
      genderSplit: { male: 48, female: 52 },
      monthlyImpressions: "42M+",
      engagementRate: "6.9%",
    },
    avatar: "/images/influencers/ghaith-marwan.jpg",
  },
];
