import {
  DigitalTwinLocation,
  EnterpriseCreatorItem,
  ObVanTechnicalSpecs,
  EnterprisePackageTier,
} from "./types";

export const DIGITAL_TWINS: DigitalTwinLocation[] = [
  {
    id: "diriyah-gate",
    name: "Diriyah At-Turaif UNESCO Heritage",
    arabicName: "بوابة الدرعية التاريخية - حي الطريف",
    region: "Riyadh",
    country: "Saudi Arabia",
    countryFlag: "🇸🇦",
    category: "Heritage & Culture",
    description:
      "Millimeter-accurate photogrammetry scan of mud-brick Najdi architecture, dynamic Arabian desert sand dust simulation, and authentic sunset solar angles.",
    unrealEngineVersion: "5.4.4 Nanite & Lumen",
    polyCount: "1.4 Billion Polygons",
    textureResolution: "16K ACES Virtual Textures",
    image: "/images/projects/flag-day.jpg",
    defaultTimeOfDay: "golden_hour",
    permitSavingsPercentage: 75,
    featuredPill: "Vision 2030 Sovereign Asset",
  },
  {
    id: "neom-sindalah",
    name: "NEOM Sindalah Island Marina",
    arabicName: "نيوم - جزيرة سندالة الفاخرة",
    region: "Tabuk / Red Sea",
    country: "Saudi Arabia",
    countryFlag: "🇸🇦",
    category: "Giga-Project",
    description:
      "Ultra-luxury Red Sea island twin with real-time dynamic water caustics, superyacht berths, and responsive biophilic architectural lighting.",
    unrealEngineVersion: "5.4.4 Nanite & Lumen",
    polyCount: "2.1 Billion Polygons",
    textureResolution: "32K Deep Ocean Shaders",
    image: "/images/projects/delos.jpg",
    defaultTimeOfDay: "high_noon",
    permitSavingsPercentage: 80,
    featuredPill: "Giga-Project Certified",
  },
  {
    id: "dubai-future-skyline",
    name: "Dubai Future Skyline & Marina",
    arabicName: "أفق دبي المستقبلي والمارينا",
    region: "Dubai",
    country: "UAE",
    countryFlag: "🇦🇪",
    category: "Metropolis",
    description:
      "Curved 180° panoramic view of Burj Khalifa, Museum of the Future, and neon waterfront reflections with live traffic density toggles.",
    unrealEngineVersion: "5.4.4 Nanite & Lumen",
    polyCount: "950 Million Polygons",
    textureResolution: "8K HDR Skyboxes",
    image: "/images/virtual-studio/dubai-composite.jpg",
    defaultTimeOfDay: "cyber_night",
    permitSavingsPercentage: 65,
    featuredPill: "Dubai 2033 Creative Hub",
  },
  {
    id: "alula-oasis",
    name: "AlUla Hegra Desert Monument",
    arabicName: "العلا - مقابر الحجر الأثرية",
    region: "Madinah Province",
    country: "Saudi Arabia",
    countryFlag: "🇸🇦",
    category: "Heritage & Culture",
    description:
      "Sandstone tomb facades carved into golden cliffs, authentic astronomical night skies with the Milky Way, and high-dynamic thermal haze.",
    unrealEngineVersion: "5.4.4 Nanite & Lumen",
    polyCount: "1.8 Billion Polygons",
    textureResolution: "16K Rock Micro-Displacement",
    image: "/images/projects/dmx.jpg",
    defaultTimeOfDay: "blue_hour",
    permitSavingsPercentage: 70,
    featuredPill: "Royal Commission Asset",
  },
];

export const ENTERPRISE_CREATORS: EnterpriseCreatorItem[] = [
  {
    id: "aboflah",
    slug: "aboflah",
    name: "Abo Flah",
    arabicName: "أبو فله",
    avatar: "/images/influencers/aboflah.jpg",
    totalFollowers: "70M+",
    rawFollowers: 70,
    niche: "Gaming, Mega-Philanthropy & GCC Youth Entertainment",
    mawthooqStatus: "Verified & Licensed",
    mawthooqLicenseId: "MWQ-882910-KSA",
    saudiReachPct: 44,
    uaeReachPct: 22,
    topAudienceAge: "16–30 (84%)",
    baseCampaignFeeAED: 180000,
    flag: "🇰🇼",
  },
  {
    id: "abir-saghir",
    slug: "abir-saghir",
    name: "Abir El Saghir",
    arabicName: "عبير الصغير",
    avatar: "/images/influencers/abir-saghir.jpg",
    totalFollowers: "72M+",
    rawFollowers: 72,
    niche: "High-End Culinary, Hospitality & Arab Heritage",
    mawthooqStatus: "Verified & Licensed",
    mawthooqLicenseId: "MWQ-743109-KSA",
    saudiReachPct: 28,
    uaeReachPct: 32,
    topAudienceAge: "20–40 (78%)",
    baseCampaignFeeAED: 160000,
    flag: "🇱🇧",
  },
  {
    id: "noor-stars",
    slug: "noor-stars",
    name: "Noor Stars",
    arabicName: "نور ستارز",
    avatar: "/images/influencers/noor-stars.jpg",
    totalFollowers: "62M+",
    rawFollowers: 62,
    niche: "Luxury Beauty, Lifestyle, Music & Broadcast Talk Shows",
    mawthooqStatus: "Verified & Licensed",
    mawthooqLicenseId: "MWQ-619024-KSA",
    saudiReachPct: 40,
    uaeReachPct: 20,
    topAudienceAge: "18–35 (80%)",
    baseCampaignFeeAED: 150000,
    flag: "🇮🇶",
  },
  {
    id: "narins-beauty",
    slug: "narins-beauty",
    name: "Narins Beauty",
    arabicName: "نارين بيوتي",
    avatar: "/images/influencers/narins-beauty.jpg",
    totalFollowers: "50M+",
    rawFollowers: 50,
    niche: "Youth Fashion, High-Energy Vlogging & Pop Culture",
    mawthooqStatus: "Verified & Licensed",
    mawthooqLicenseId: "MWQ-552190-KSA",
    saudiReachPct: 38,
    uaeReachPct: 24,
    topAudienceAge: "16–28 (86%)",
    baseCampaignFeeAED: 130000,
    flag: "🇸🇾",
  },
];

export const OB_VAN_SPECS: ObVanTechnicalSpecs = {
  model: "Mercedes Actros Heavy-Duty Broadcast Unit (Yas Mobile Command)",
  broadcastStandard: "4K UHD 12G-SDI / SMPTE ST 2110 IP Ready",
  camerasCount: "12x Sony HDC-4300 4K High-Speed Optical Chains",
  opticalFiberRuns: "Up to 5 km Tactical Armor Fiber Cables per Node",
  replayEngine: "Dual EVS XT-VIA 12-Channel Live Slow-Motion & Ingest",
  audioInfrastructure: "Calrec Artemis Light 48-Fader Digital Console with Dolby Atmos",
  uplinkLatency: "Sub-1.2s via Dual Ku/Ka Band Satellite & Private 5G Slice",
  powerRedundancy: "Dual 60kVA Silenced On-Board Generators with Auto-Failover UPS",
  operationalRadius: ["UAE (Abu Dhabi, Dubai)", "Saudi Arabia (Riyadh, Jeddah, AlUla)", "Egypt & Jordan"],
};

export const ENTERPRISE_TIERS: EnterprisePackageTier[] = [
  {
    id: "national-tier",
    name: "Government & National Campaigns",
    arabicName: "حزمة الجهات الحكومية والمؤسسات الوطنية",
    targetClientele: "Government Ministries, Sovereign Authorities & Tourism Boards",
    monthlyInvestment: "AED 75,000",
    yearlyInvestment: "AED 750,000 / year",
    currency: "AED",
    features: [
      "Guaranteed 5 Soundstage Production Days per month",
      "Full Cinema Crew (Director, DP, Sound, Gaffer, Drone)",
      "Dedicated UAE & Saudi Location Permits Expeditor",
      "Unreal Engine 5.4 Digital Twin Asset Licensing",
      "Dolby Atmos Broadcast 4K Masters & Social Deliverables",
      "Confidentiality & National Security NDA Protocol",
    ],
    slaGuarantee: "24-Hour Production Mobilization across Dubai & Riyadh",
    popular: false,
  },
  {
    id: "giga-tier",
    name: "Giga-Project & Broadcast Retainer",
    arabicName: "حزمة المشاريع الكبرى والبث الميداني المتقدم",
    badge: "Most Comprehensive",
    targetClientele: "NEOM, Red Sea Global, Sports Federations, Telecoms & Arenas",
    monthlyInvestment: "AED 140,000",
    yearlyInvestment: "AED 1,400,000 / year",
    currency: "AED",
    features: [
      "12-Camera 4K OB-VAN Deployment (2 Major Live Events/month)",
      "Unreal 5.4 In-Camera VFX Virtual Studio Stage Access (Unlimited)",
      "Dual EVS Slow-Mo & Instant 8-Second AI Viral Clip Syndication",
      "Mawthooq-Audited Multi-Creator Campaigns (SARIE/Aani Escrow)",
      "Bespoke Photogrammetry Digital Twin Asset Development",
      "Dedicated Senior Executive Producer & 24/7 Operations Room",
    ],
    slaGuarantee: "4-Hour Critical Emergency Broadcast Deployment",
    popular: true,
  },
  {
    id: "brand-creator-suite",
    name: "Brand & Creator Growth Engine",
    arabicName: "حزمة العلامات التجارية والإنتاج الإعلاني المتسارع",
    targetClientele: "Multinational FMCG, Tech Enterprises & Advertising Networks",
    monthlyInvestment: "AED 45,000",
    yearlyInvestment: "AED 480,000 / year",
    currency: "AED",
    features: [
      "3 Turnkey Commercial Video Productions per month",
      "Direct Booking with Yas Pro Exclusive Creators (AboFlah, Noor Stars)",
      "Saudi GAMR Mawthooq Full Regulatory Verification & Compliance Audit",
      "Multi-Dialect Localization (Emirati, Najdi, Egyptian, Levantine)",
      "Same-Day Turnkey 9:16 Social Cutdowns & TikTok Ads",
      "Dedicated Account Manager & Cloud Asset Archive (10TB)",
    ],
    slaGuarantee: "48-Hour Turnaround from Shoot to Final Master",
    popular: false,
  },
];

export const ENTERPRISE_STATS = [
  { value: "250M+", label: "Creator Network Reach", sublabel: "Verified Middle East Audiences" },
  { value: "12 Channels", label: "4K Live Broadcast", sublabel: "OB-Van Tactical Fiber Feeds" },
  { value: "65–80%", label: "Location Cost Reduction", sublabel: "Via Unreal Engine 5.4 Virtual Sets" },
  { value: "100%", label: "GAMR Mawthooq Compliant", sublabel: "Saudi & UAE Regulatory Clearance" },
];
