import { ProjectItem, ProjectCategory } from "./types";

export const PROJECTS_DATA: ProjectItem[] = [
  {
    id: "flag-day",
    slug: "flag-day",
    title: "UAE Flag Day Official Film",
    arabicTitle: "يوم العلم الإماراتي",
    category: "government",
    categoryLabel: "Government",
    client: "UAE National Media Office",
    description: "Official national celebration film honoring unity, heritage, and pride across Dubai and Abu Dhabi iconic landmarks.",
    tag: "National Campaign",
    views: "15M+ Views",
    year: "2024",
    vimeoId: "1093240200",
    image: "/images/projects/flag-day.jpg",
    deliverables: ["Official 4K Broadcast Master", "Cinema Festival Cut", "Social Media Cutdowns (9:16 & 1:1)"],
    techStack: ["ARRI Alexa Mini LF", "Heavy-Lift Cinema Drones", "Live Fiber Feeds", "Dolby Atmos Mastering"],
  },
  {
    id: "dmx",
    slug: "dmx",
    title: "Dubai Municipality Academy (DMX)",
    arabicTitle: "أكاديمية بلدية دبي",
    category: "government",
    categoryLabel: "Government",
    client: "Dubai Municipality",
    description: "Documenting Dubai Municipality's vision through the milestone launch of its first accredited professional academy, combined with high-end 3D architectural CGI.",
    tag: "Government & CGI",
    views: "18M+ Views",
    year: "2024",
    vimeoId: "1093240277",
    image: "/images/projects/dmx.jpg",
    deliverables: ["Launch Film Master", "3D CGI Architectural Tour", "VIP Keynote Presentation"],
    techStack: ["Unreal Engine 5.4 CGI", "RED V-Raptor XL 8K", "Motion Control Crane", "Spatial Sound Design"],
  },
  {
    id: "stadiums-dubai",
    slug: "stadiums-dubai",
    title: "Dubai Sports & Venues Experience",
    arabicTitle: "تجربة ملاعب دبي الرياضية",
    category: "government",
    categoryLabel: "Government",
    client: "Dubai Sports Council",
    description: "Dynamic multi-camera and high-speed FPV visual journey through world-class stadiums and sports parks across Dubai.",
    tag: "Sports & Venues",
    views: "25M+ Views",
    year: "2024",
    vimeoId: "1093240277",
    image: "/images/projects/dm-sport.jpg",
    deliverables: ["Sports Council Showcase Master", "Stadium Big-Screen Intros", "Viral Social Reel Campaign"],
    techStack: ["RED V-Raptor XL 8K", "High-Speed FPV Drone", "Phantom Flex 4K", "Color Front Grading"],
  },
  {
    id: "orange-ramadan",
    slug: "orange-ramadan",
    title: "Orange Telecom Ramadan Campaign",
    arabicTitle: "إعلان أورنج الرمضاني",
    category: "commercial",
    categoryLabel: "TV Commercial",
    client: "Orange Telecom",
    description: "High-budget television commercial celebrating the warmth, connection, and human spirit of the holy month across regional broadcast networks.",
    tag: "TV Commercial",
    views: "35M+ Views",
    year: "2024",
    vimeoId: "892576562",
    videoUrl: "/videos/projects/salon-hair-commercial.mp4",
    image: "/images/projects/orange.jpg",
    deliverables: ["60s National TVC Master", "30s Digital Primetime Cuts", "Broadcast Audio Mastering"],
    techStack: ["ARRI Alexa 35", "Cooke Anamorphic /i Full Frame", "Set Construction", "Dolby Digital 5.1"],
  },
  {
    id: "delos-living",
    slug: "delos-living",
    title: "Delos Wellness Living Architecture",
    arabicTitle: "ديلوس للعمارة الصحية الفاخرة",
    category: "commercial",
    categoryLabel: "Commercial Film",
    client: "Delos Living UAE",
    description: "Luxury architectural showcase highlighting biophilic design, smart wellness air systems, and ultra-prime Dubai residential engineering.",
    tag: "Luxury Architecture",
    views: "12M+ Views",
    year: "2024",
    vimeoId: "886007699",
    videoUrl: "/videos/reels/product-commercial-reel.mp4",
    image: "/images/projects/delos.jpg",
    deliverables: ["Cinema TV Spot", "Global Architectural Vignettes", "Developer Master Package"],
    techStack: ["ARRI Alexa Mini LF", "Master Prime Optics", "Bespoke Orchestral Score", "HDR10 Delivery"],
  },
  {
    id: "kananya-jewelry",
    slug: "kananya-jewelry",
    title: "Kananya Horse Fine Jewelry",
    arabicTitle: "مجوهرات كنانيا المستوحاة من الخيل",
    category: "commercial",
    categoryLabel: "Fashion & Luxury",
    client: "Kananya Fine Jewelry",
    description: "Creative cinematic commercial capturing horse-inspired luxury fine jewelry with high-speed macro optics and evocative lighting.",
    tag: "High Fashion",
    views: "14M+ Views",
    year: "2024",
    vimeoId: "886084096",
    videoUrl: "/videos/reels/fb-tabletop-cinema.mp4",
    image: "/images/projects/kananya.jpg",
    deliverables: ["Director's Cut 4K Film", "Macro Jewelry Showreel", "Social Campaign Suite"],
    techStack: ["Phantom Flex 4K High Speed", "Laowa Probe Macro", "Aputure Optical Snoot", "Fine Color Grade"],
  },
  {
    id: "talabat-campaign",
    slug: "talabat-campaign",
    title: "Talabat Regional Brand Film",
    arabicTitle: "حملة طلبات الإقليمية",
    category: "commercial",
    categoryLabel: "Commercial Film",
    client: "Talabat Delivery",
    description: "High-energy commercial narrative showcasing fast-paced city lifestyle, creator deliveries, and street-level cinematic energy.",
    tag: "Commercial Film",
    views: "22M+ Views",
    year: "2024",
    vimeoId: "886084148",
    videoUrl: "/videos/projects/talabat-breakfast-commercial.mp4",
    image: "/images/projects/talabat.jpg",
    deliverables: ["Regional TV Commercial", "Digital Billboard Loop", "Social Interactive Ads"],
    techStack: ["Sony FX9 Rigs", "Ronin 4D Gimbal System", "Dynamic Motion Design", "Sound Mix"],
  },
  {
    id: "zain-telecom",
    slug: "zain-telecom",
    title: "Zain 5G Commercial Campaign",
    arabicTitle: "إعلان زين للاتصالات",
    category: "commercial",
    categoryLabel: "TV Commercial",
    client: "Zain Group",
    description: "Futuristic visual storytelling highlighting ultra-fast connectivity, digital communities, and youth creators in the Gulf region.",
    tag: "Telecom Broadcast",
    views: "28M+ Views",
    year: "2024",
    vimeoId: "892576633",
    image: "/images/projects/zain.jpg",
    deliverables: ["Broadcast TV Commercial", "Cinema Pre-Roll Masters", "Outdoor LED Billboard Stems"],
    techStack: ["RED V-Raptor 8K", "VFX Wire Removal", "Color Grading DaVinci Studio", "Commercial Licences"],
  },
  {
    id: "gitex-global",
    slug: "gitex-global",
    title: "GITEX Global AI & Tech Highlights",
    arabicTitle: "تغطية جيتكس جلوبال للذكاء الاصطناعي",
    category: "shows",
    categoryLabel: "Live Shows & Events",
    client: "Dubai World Trade Centre",
    description: "Comprehensive multi-camera and OB-Van live broadcast coverage of the world's biggest AI and technology exhibition.",
    tag: "Tech Summit & Live",
    views: "30M+ Views",
    year: "2024",
    vimeoId: "1093239331",
    image: "/images/projects/gitex.jpg",
    deliverables: ["Keynote Live Broadcast Master", "Daily AI Recap Series", "VIP Executive Interviews"],
    techStack: ["Mobile OB-VAN Live Switcher", "SMPTE Fiber Runs", "PTZ Remote Network", "Live Cloud Multistream"],
  },
];

export const PROJECT_CATEGORIES: { id: ProjectCategory; label: string; arabicLabel?: string }[] = [
  { id: "all", label: "All Works", arabicLabel: "الكل" },
  { id: "government", label: "Government & National", arabicLabel: "حكومي ووطني" },
  { id: "commercial", label: "TV Commercials & Brands", arabicLabel: "إعلانات وتجاري" },
  { id: "shows", label: "Shows & Events", arabicLabel: "برامج وفعاليات" },
];
