import { Sparkles, Camera, Radio, Users, Award, ShieldCheck, Clapperboard, Globe2 } from "lucide-react";

export interface TeamMember {
  role: string;
  arRole: string;
  name: string;
  arName: string;
  focus: string;
  arFocus: string;
  initials: string;
  department: string;
  arDepartment: string;
  gradient: string;
}

export const TEAM_MEMBERS: TeamMember[] = [
  {
    role: "CEO & Founder",
    arRole: "الرئيس التنفيذي والمؤسس",
    name: "Yaman Mohammad Alomari",
    arName: "يمان محمد العمري",
    focus: "Strategic growth, government media partnerships & sovereign GCC infrastructure expansion",
    arFocus: "النمو الاستراتيجي، الشراكات الإعلامية الحكومية، والتوسع السيادي في الخليج",
    initials: "YA",
    department: "Executive Board",
    arDepartment: "مجلس الإدارة التنفيذي",
    gradient: "from-amber-600 via-amber-500 to-yellow-400",
  },
  {
    role: "Chief Technology Officer",
    arRole: "المدير التقني التنفيذي",
    name: "Broadcast & AI Systems Lead",
    arName: "إدارة أنظمة البث والذكاء الاصطناعي",
    focus: "Real-time AI video ingestion, SMPTE 2110 IP fabric & neural virtual production pipeline",
    arFocus: "معالجة الفيديو بالذكاء الاصطناعي اللحظي، شبكات SMPTE 2110، والاستوديوهات الافتراضية العصبية",
    initials: "CTO",
    department: "Media Engineering",
    arDepartment: "الهندسة الإعلامية والتقنية",
    gradient: "from-amber-500 via-stone-600 to-emerald-400",
  },
  {
    role: "Head of Studio Operations",
    arRole: "رئيس إدارة وتشغيل الاستوديوهات",
    name: "Soundstages & Production Ops",
    arName: "إدارة الاستوديوهات والتشغيل",
    focus: "Multi-facility soundstage allocations, tier-one talent workflow & client set coordination",
    arFocus: "تخصيص استوديوهات التصوير الكبرى، مسارات إنتاج النخبة، والتنسيق الميداني الشامل",
    initials: "OPS",
    department: "Physical Studios",
    arDepartment: "الاستوديوهات الميدانية",
    gradient: "from-amber-500 via-amber-600 to-yellow-500",
  },
  {
    role: "OB-VAN & Live Broadcast Director",
    arRole: "مدير البث المباشر وأساطيل النقل الخارجي",
    name: "Outside Broadcast Operations",
    arName: "عمليات البث الميداني والفضائي",
    focus: "Stadium live sports multi-cam switching, EVS instant replay & mobile satellite telemetry",
    arFocus: "إدارة البث الرياضي متعدد الكاميرات، إعادة EVS اللحظية، والاتصالات الفضائية المتنقلة",
    initials: "OB",
    department: "Tactical Fleet",
    arDepartment: "أسطول البث التكتيكي",
    gradient: "from-amber-600 via-stone-700 to-amber-500",
  },
  {
    role: "Director of Sound & Spatial Audio",
    arRole: "مدير هندسة الصوت والصوت المحيطي",
    name: "Acoustics & Dolby Atmos",
    arName: "الصوتيات وهندسة دولبي أتموس",
    focus: "Acoustic room calibration, cinema surround mastering & AI spatial voice isolation",
    arFocus: "معايرة الغرف الصوتية، المكساج السينمائي المحيطي، وعزل الصوت العصبي بالذكاء الاصطناعي",
    initials: "ATM",
    department: "Audio Engineering",
    arDepartment: "الهندسة الصوتية",
    gradient: "from-amber-600 via-amber-500 to-amber-400",
  },
  {
    role: "Lead Virtual Production Cinematographer",
    arRole: "مدير التصوير والإنتاج الافتراضي",
    name: "Optics & Camera Chains",
    arName: "إدارة البصريات والكاميرات السينمائية",
    focus: "Unreal Engine 5.4 in-camera VFX (ICVFX), LED wall genlock & ARRI/RED optics optimization",
    arFocus: "المؤثرات البصرية داخل الكاميرا ICVFX، مزامنة شاشات LED، وتوجيه العدسات السينمائية",
    initials: "CIN",
    department: "Virtual Cinematography",
    arDepartment: "التصوير السينمائي الافتراضي",
    gradient: "from-zinc-700 via-stone-600 to-amber-600",
  },
];

export const PILLARS = [
  {
    icon: Sparkles,
    badge: "Neural Workflows",
    arBadge: "مسارات ذكية",
    title: "AI-Integrated Workflows",
    arTitle: "مسارات عمل مدعومة بالذكاء الاصطناعي",
    description: "Harnessing real-time generative AI for automated shot logging, dialect adaptation, neural color transforms, and instantaneous multi-camera clipping.",
    arDescription: "تسخير الذكاء الاصطناعي التوليدي الفوري لأرشفة اللقطات الذكية، تكييف اللهجات، المعالجة اللونية، والنشر اللحظي متعدد الزوايا.",
    tags: ["Unreal Engine 5.4", "Dialect AI", "Instant Replay", "Neural Upscaling"],
    gradient: "from-amber-500 to-amber-700",
  },
  {
    icon: Camera,
    badge: "Cinema Soundstages",
    arBadge: "استوديوهات سينمائية",
    title: "State-of-the-Art Studios",
    arTitle: "استوديوهات بأعلى المواصفات العالمية",
    description: "Purpose-built acoustic environments with automated digital lighting grids, 8K dual-ISO camera chains, podcast suites, and flexible luxury set dressing.",
    arDescription: "بيئات صوتية معزولة بأحدث شبكات الإضاءة الرقمية، سلاسل كاميرات 8K، أجنحة البودكاست الاحترافية، وتجهيزات ديكور مرنة تلبي أعلى المعايير.",
    tags: ["8K RAW", "Acoustic NC-20", "DMX Lighting", "Podcast Suites"],
    gradient: "from-amber-600 to-yellow-600",
  },
  {
    icon: Radio,
    badge: "Tactical Mobility",
    arBadge: "جاهزية ميدانية",
    title: "Broadcast-Grade Mobility",
    arTitle: "بث تلفزيوني خارجي فائق الجاهزية",
    description: "Heavy-duty OB-VAN mobile control command units equipped with dark-fiber, satellite uplinks, and redundant generators for arenas and national summits.",
    arDescription: "عربات نقل خارجي (OB-VAN) متطورة مجهزة بالألياف الضوئية المظلمة، اتصالات الأقمار الصناعية، ومولدات طوارئ للفعاليات والملاعب الرياضية.",
    tags: ["OB-VAN Fleet", "SMPTE 2110", "Fiber Runs", "Dual Satellite"],
    gradient: "from-amber-500 to-amber-600",
  },
  {
    icon: Users,
    badge: "Creator Network",
    arBadge: "شبكة المبدعين",
    title: "Creator-First Ecosystem",
    arTitle: "منظومة إنتاجية متكاملة لصناع المحتوى",
    description: "End-to-end format incubation, commercial sponsorships, and episodic television production designed for top-tier creators commanding 400M+ impressions.",
    arDescription: "حضانة وتطوير برامج وبودكاست ورعايات تجارية كبرى مخصصة لنخبة صناع المحتوى المؤثرين الذين يتجاوز وصولهم 400 مليون مشاهدة.",
    tags: ["400M+ Audience", "Episodic Series", "Brand Deals", "Syndication"],
    gradient: "from-amber-500 to-amber-600",
  },
];

export const REGIONAL_HUBS_EXPANDED = [
  {
    id: "dubai",
    cityEn: "Dubai, UAE",
    cityAr: "دبي، الإمارات",
    titleEn: "Global Headquarters & Main Stages",
    titleAr: "المقر الرئيسي والاستوديوهات الكبرى",
    facilityEn: "Iris Bay Tower, Business Bay",
    facilityAr: "برج إيريس باي، الخليج التجاري",
    stats: "3 Soundstages • 4K Control Hub • OB-VAN Unit 1",
    arStats: "3 استوديوهات تصوير • غرفة تحكم 4K • عربة بث ميداني 1",
    badge: "Primary HQ",
    arBadge: "المقر الرئيسي",
    flag: "🇦🇪",
    status: "Active 24/7",
    arStatus: "تشغيل 24/7",
    color: "amber",
  },
  {
    id: "cairo",
    cityEn: "Cairo, Egypt",
    cityAr: "القاهرة، مصر",
    titleEn: "Regional Post-Production & Color Hub",
    titleAr: "مركز ما بعد الإنتاج والمكساج اللوني",
    facilityEn: "Elite Tower, Zahraa Al Maadi",
    facilityAr: "برج إيليت، زهراء المعادي",
    stats: "Dolby Atmos Studio • DaVinci 8K Grading Suites",
    arStats: "استوديو دولبي أتموس • أجنحة تلوين دافينشي 8K",
    badge: "Post Hub",
    arBadge: "مركز ما بعد الإنتاج",
    flag: "🇪🇬",
    status: "Online",
    arStatus: "نشط ومتصل",
    color: "emerald",
  },
  {
    id: "amman",
    cityEn: "Amman, Jordan",
    cityAr: "عَمّان، الأردن",
    titleEn: "Levant Regional Studio & Dispatch",
    titleAr: "استوديو بلاد الشام وفرق التصوير الميداني",
    facilityEn: "BlackRock Tower, Mecca St",
    facilityAr: "برج بلاك روك، شارع مكة",
    stats: "Acoustic Podcast Stage • Mountain Cinematic Rigs",
    arStats: "استوديو بودكاست معزول • أطقم تصوير التضاريس الخارجية",
    badge: "Levant Hub",
    arBadge: "مقر بلاد الشام",
    flag: "🇯🇴",
    status: "Online",
    arStatus: "نشط ومتصل",
    color: "amber",
  },
];

export const ACCREDITATIONS = [
  {
    icon: ShieldCheck,
    titleEn: "UAE National Media Council",
    titleAr: "المجلس الوطني للإعلام بدولة الإمارات",
    descEn: "Officially licensed and accredited since 2015 under UAE NMC media regulations.",
    descAr: "ترخيص واعتماد رسمي ساري منذ عام 2015 وفق أعلى المعايير التنظيمية الإعلامية.",
  },
  {
    icon: Award,
    titleEn: "FTA Corporate Tax & VAT Compliant",
    titleAr: "امتثال ضريبي كامل للهيئة الاتحادية للضرائب",
    descEn: "Transparent enterprise auditing, legal invoicing & official governmental supplier registry.",
    descAr: "فواتير ضريبية نظامية وتسجيل رسمي معتمد لدى منصات المشتريات الحكومية.",
  },
  {
    icon: Clapperboard,
    titleEn: "ARRI & RED Certified Cinema Stages",
    titleAr: "استوديوهات معتمدة لأنظمة ARRI و RED",
    descEn: "Standardized optical pipelines, verified anamorphic optics, and RAW 8K genlock calibration.",
    descAr: "مسارات بصرية سينمائية متطابقة ومعايرة دقيقة لأنظمة الكاميرات السينمائية العالمية.",
  },
  {
    icon: Globe2,
    titleEn: "Sovereign Confidentiality & Security",
    titleAr: "سرية تامة وأمن بيانات سيادي",
    descEn: "Air-gapped on-premise storage and non-disclosure agreements for ministries and giga-projects.",
    descAr: "خوادم تخزين محلية معزولة واتفاقيات سرية بيانات صارمة لحملات الوزارات والمشاريع السيادية.",
  },
];
