import { GearCategory, GearItem } from "./types";

export const GEAR_DATA: GearItem[] = [
  {
    id: "arri-alexa-mini-lf",
    name: "ARRI Alexa Mini LF",
    category: "cameras",
    categoryLabel: "Cinema Camera",
    dailyRate: 3500,
    securityDeposit: 5000,
    image: "/images/gear/arri-alexa-mini-lf.jpg",
    specs: ["Large Format 4.5K Sensor", "ProRes & ARRIRAW", "LPL & PL Mount"],
    description: "Industry standard cinema camera package with viewfinder, cage, and battery plate.",
    isPopular: true,
  },
  {
    id: "arri-commercial-cinema-kit",
    name: "ARRI Master Commercial Package",
    category: "bundles",
    categoryLabel: "Turnkey Cinema Kit",
    dailyRate: 6500,
    securityDeposit: 8000,
    image: "/images/gear/arri-commercial-cinema-kit.jpg",
    isKit: true,
    includedInKit: [
      "ARRI Alexa Mini LF + MVF-2",
      "Cooke S4/i 3-Lens Trio (25, 50, 75mm)",
      "Teradek Bolt 4K Wireless Transmitter",
      "SmallHD 703 Ultra-Brite Wireless Monitor",
      "Arri MMB-2 Matte Box + Tilta Nucleus-M",
      "4x 150Wh V-Mount Batteries & Quad Charger",
    ],
    specs: ["Turnkey 4.5K Cinema Master", "Full Wireless Director Video", "Wireless Focus & Matte Box"],
    description: "Ready-to-roll A-camera package calibrated for high-budget UAE commercial campaigns and prestige music videos.",
    isPopular: true,
  },
  {
    id: "red-v-raptor-xl",
    name: "RED V-Raptor XL 8K VV",
    category: "cameras",
    categoryLabel: "Cinema Camera",
    dailyRate: 2800,
    securityDeposit: 4500,
    image: "/images/gear/red-v-raptor-xl.jpg",
    specs: ["8K VV Multi-Format", "High-speed 120fps @ 8K", "Integrated I/O"],
    description: "Ultimate high-resolution cinema system designed for commercial and dynamic productions.",
  },
  {
    id: "sony-fx6-run-gun-kit",
    name: "Sony FX6 Commercial Run & Gun Kit",
    category: "bundles",
    categoryLabel: "Creator & Doc Kit",
    dailyRate: 1850,
    securityDeposit: 2500,
    image: "/images/gear/sony-fx6-run-gun-kit.jpg",
    isKit: true,
    includedInKit: [
      "Sony FX6 Full-Frame Cinema Line Body",
      "Sony FE 24-70mm f/2.8 GM II",
      "DJI Mic 2 Dual Wireless Transmitters",
      "Atomos Ninja V+ 8K RAW Monitor/Recorder",
      "Tilta Cage + Gold Mount Battery Rig",
    ],
    specs: ["Ultra-fast Autofocus + Dual Base ISO", "Wireless Audio Direct to Camera", "ProRes RAW External Recording"],
    description: "The #1 chosen kit by Dubai creators and documentary crews for fast, cinematic handheld shooting.",
    isPopular: true,
  },
  {
    id: "sony-fx9-package",
    name: "Sony FX9 Full-Frame Package",
    category: "cameras",
    categoryLabel: "Broadcast / Doc Camera",
    dailyRate: 1200,
    securityDeposit: 2000,
    image: "/images/gear/sony-fx9-package.jpg",
    specs: ["6K Full-Frame Sensor", "Fast Hybrid AF", "Dual Base ISO"],
    description: "Ideal for documentary, multicam reality, and on-location live broadcast.",
  },
  {
    id: "cooke-s4i-set",
    name: "Cooke S4/i Prime Lens Set (5 Lenses)",
    category: "lenses",
    categoryLabel: "Prime Lenses",
    dailyRate: 2200,
    securityDeposit: 4000,
    image: "/images/gear/cooke-s4i-set.jpg",
    specs: ["18mm, 25mm, 35mm, 50mm, 75mm", "T2.0 Aperture", "Cooke Look Warmth"],
    description: "Classic cinema primes offering natural skin tones and signature cinematic roll-off.",
    isPopular: true,
  },
  {
    id: "aputure-600c-pro",
    name: "Aputure LS 600c Pro RGBWW Kit",
    category: "lighting",
    categoryLabel: "Studio Lighting",
    dailyRate: 650,
    securityDeposit: 1000,
    image: "/images/gear/aputure-600c-pro.jpg",
    specs: ["600W Full-Color Point Source", "IP54 Weather-resistant", "Sidus Link Control"],
    description: "Heavy-duty color-tunable fixture for creative studio sets and high-output commercial setups.",
  },
  {
    id: "aputure-master-gaffer-kit",
    name: "Master Gaffer Commercial Lighting Suite",
    category: "bundles",
    categoryLabel: "Turnkey Lighting Rig",
    dailyRate: 2400,
    securityDeposit: 3500,
    image: "/images/gear/aputure-master-gaffer-kit.jpg",
    isKit: true,
    includedInKit: [
      "1x Aputure LS 1200d Pro Daylight Fixture",
      "2x Aputure LS 600c Pro RGBWW Point Sources",
      "8x Astera Titan Wireless Pixel Tubes + Case",
      "Light Dome 150 + Lantern 90 Softboxes",
      "Heavy-duty C-Stands, Sandbags & Grip Clamps",
    ],
    specs: ["1200W Daylight Punch + Full RGBWW", "Complete Wireless App Mesh Control", "Grip, Diffusion & Stands Included"],
    description: "Full soundstage and location lighting package capable of lighting complete commercial sets in Dubai.",
    isPopular: true,
  },
  {
    id: "astera-titan-tubes-kit",
    name: "Astera Titan Tube 8-Light Kit",
    category: "lighting",
    categoryLabel: "Wireless Pixel Lighting",
    dailyRate: 950,
    securityDeposit: 1500,
    image: "/images/gear/astera-titan-tubes-kit.jpg",
    specs: ["8x Pixel Tubes with Charging Case", "Wireless CRMX & App", "Tunable White & RGB"],
    description: "Must-have lighting kit for podcast backdrops, music videos, and ambient neon sets.",
    isPopular: true,
  },
  {
    id: "sennheiser-mkh416-kit",
    name: "Sennheiser MKH 416 Boom Kit",
    category: "audio",
    categoryLabel: "Location Audio",
    dailyRate: 350,
    securityDeposit: 600,
    image: "/images/gear/sennheiser-mkh416-kit.jpg",
    specs: ["Industry Standard Shotgun Mic", "Rycote Windshield & Blimp", "Carbon Fiber Boom Pole"],
    description: "Broadcast-grade dialogue pickup with excellent feedback rejection and moisture resistance.",
  },
  {
    id: "podcast-studio-bundle",
    name: "4-Person Podcast Gear Bundle",
    category: "bundles",
    categoryLabel: "Complete Bundle",
    dailyRate: 1900,
    securityDeposit: 2500,
    image: "/images/gear/podcast-studio-bundle.jpg",
    isKit: true,
    includedInKit: [
      "4x Shure SM7B Dynamic Vocal Microphones",
      "RØDECaster Pro II Audio Production Console",
      "3x Sony 4K PTZ / Cinema Cameras",
      "Blackmagic ATEM Mini Extreme ISO Switcher",
      "4x Audio-Technica Studio Headphones",
      "Acoustic Arms & XLR Cabling",
    ],
    specs: ["4x Shure SM7B Mics + RØDECaster Pro II", "3x 4K Sony Cameras + ATEM Switcher", "Astera Mood Lights"],
    description: "Turnkey multi-camera live switching setup ready for turnkey podcast recording anywhere in the UAE.",
    isPopular: true,
  },
  {
    id: "ob-van-live-pack",
    name: "OB-VAN Mobile Broadcast Unit",
    category: "bundles",
    categoryLabel: "Broadcast Rig",
    dailyRate: 12500,
    securityDeposit: 15000,
    image: "/images/gear/ob-van-live-pack.jpg",
    isKit: true,
    includedInKit: [
      "Mercedes Heavy-Duty Mobile OB Van with 8 Workstations",
      "6x Sony HDC-4300 4K/HD System Cameras with Fiber CCUs",
      "Fujinon 4K UHD Broadcast Zoom Lenses (including 107x Box Lens)",
      "Grass Valley Live Production Switcher",
      "EVS Live Slow Motion & Video Server",
      "Full On-Board Crew (Engineer in Charge, Vision Mixer, Audio Lead)",
    ],
    specs: ["6x 4K Broadcast Camera Channels", "Live Replay & Slow Motion", "Dedicated Audio & Director Station"],
    description: "Turnkey outside broadcast truck with full engineering crew for stadium, concert, or festival live streaming across GCC.",
  },
];

export const GEAR_CATEGORIES: { id: GearCategory; label: string }[] = [
  { id: "all", label: "All Gear" },
  { id: "bundles", label: "Turnkey Bundles & Kits" },
  { id: "cameras", label: "Cameras" },
  { id: "lenses", label: "Lenses" },
  { id: "lighting", label: "Lighting" },
  { id: "audio", label: "Audio" },
];
