import { GearItem } from "./types";

/**
 * Production inventory imported from legacy Yas Pro WordPress store catalog.
 * Extracted, verified, and curated from u363039021_yaspro.sql WooCommerce products.
 */
export const WORDPRESS_GEAR_INVENTORY: GearItem[] = [
  {
    id: "dzo-film-cinema-hard-case-lenses-box",
    name: "DZO FILM CINEMA HARD CASE LENSES BOX",
    category: "lenses",
    categoryLabel: "Cinema Lens",
    dailyRate: 1500.0,
    securityDeposit: 2250,
    image: "/images/gear/catalog/DZO-FILM_CINEMA-HARD-CASE-LENSES-BOX.jpg",
    specs: ["Pro Studio Gear"],
    description: "Technical Specifications: Type: Hard protective lens case Capacity: 6-8 cinema primes Interior: Custom foam with compartments Shell: Heavy-duty polycarbonate...",
  },
  {
    id: "dzo-film-vespid-prime-25mm-t2-1",
    name: "DZO FILM VESPID PRIME 25MM / T2.1",
    category: "lenses",
    categoryLabel: "Cinema Lens",
    dailyRate: 250.0,
    securityDeposit: 375,
    image: "/images/gear/catalog/DZO-FILM_VESPID-PRIME-25MM-_-T2.1.jpg",
    specs: ["Pro Studio Gear"],
    description: "Technical Specifications: Type: Cinema prime lens Focal Length: 25mm wide-angle Aperture: T2.1-T22 (Manual iris) Mount: Metric or EF mount Elements: Multi-el...",
  },
  {
    id: "dzo-film-vespid-prime-35mm-t2-1",
    name: "DZO FILM VESPID PRIME 35MM / T2.1",
    category: "lenses",
    categoryLabel: "Cinema Lens",
    dailyRate: 250.0,
    securityDeposit: 375,
    image: "/images/gear/catalog/DZO-FILM_VESPID-PRIME-35MM-_-T2.1.jpg",
    specs: ["Pro Studio Gear"],
    description: "Technical Specifications: Type: Cinema prime lens Focal Length: 35mm classic narrative Aperture: T2.1-T22 Mount: Metric or EF mount Elements: Premium multi-e...",
  },
  {
    id: "dzo-film-vespid-prime-50mm-t2-1",
    name: "DZO FILM VESPID PRIME 50MM / T2.1",
    category: "lenses",
    categoryLabel: "Cinema Lens",
    dailyRate: 250.0,
    securityDeposit: 375,
    image: "/images/gear/catalog/DZO-FILM_VESPID-PRIME-50MM-_-T2.1.jpg",
    specs: ["Pro Studio Gear"],
    description: "Technical Specifications: Type: Cinema prime lens Focal Length: 50mm natural perspective Aperture: T2.1-T22 Mount: Metric or EF mount Elements: Premium optic...",
  },
  {
    id: "dzo-film-vespid-prime-75mm-t2-1",
    name: "DZO FILM VESPID PRIME 75MM / T2.1",
    category: "lenses",
    categoryLabel: "Cinema Lens",
    dailyRate: 250.0,
    securityDeposit: 375,
    image: "/images/gear/catalog/DZO-FILM_VESPID-PRIME-75MM-_-T2.1.jpg",
    specs: ["Pro Studio Gear"],
    description: "Technical Specifications: Type: Cinema prime lens Focal Length: 70mm medium telephoto Aperture: T2.1-T22 Mount: Metric or EF mount Elements: Complex telephot...",
  },
  {
    id: "dzo-film-vespid-prime-100mm-t2-1",
    name: "DZO FILM VESPID PRIME 100MM / T2.1",
    category: "lenses",
    categoryLabel: "Cinema Lens",
    dailyRate: 250.0,
    securityDeposit: 375,
    image: "/images/gear/catalog/DZO-FILM_VESPID-PRIME-100MM-_-T2.1.jpg",
    specs: ["Pro Studio Gear"],
    description: "Technical Specifications: Type: Cinema telephoto prime Focal Length: 100mm strong telephoto Aperture: T2.1-T22 Mount: Metric or EF mount Elements: Complex te...",
  },
  {
    id: "dzo-film-vespid-prime-125mm-t2-1",
    name: "DZO FILM VESPID PRIME 125MM / T2.1",
    category: "lenses",
    categoryLabel: "Cinema Lens",
    dailyRate: 250.0,
    securityDeposit: 375,
    image: "/images/gear/catalog/DZO-FILM_VESPID-PRIME-125MM-_-T2.1.jpg",
    specs: ["Pro Studio Gear"],
    description: "Technical Specifications: Type: Cinema telephoto prime Focal Length: 125mm ultra-telephoto Aperture: T2.1-T22 Mount: Metric or EF mount Elements: Advanced te...",
  },
  {
    id: "sigma-mc-11",
    name: "SIGMA MC-11",
    category: "cameras",
    categoryLabel: "Production Gear",
    dailyRate: 350.0,
    securityDeposit: 525,
    image: "/images/gear/arri-alexa-mini-lf.jpg",
    specs: ["Pro Studio Gear"],
    description: "Technical Specifications: Type: Smart mount adapter Function: EF-mount to Sony E-mount Electronic: Full autofocus communication Image Stabilization: Passes I...",
  },
  {
    id: "sigma-105mm-macro-lens-f1-4",
    name: "SIGMA 105MM MACRO LENS / F1.4",
    category: "lenses",
    categoryLabel: "Cinema Lens",
    dailyRate: 90.0,
    securityDeposit: 135,
    image: "/images/gear/catalog/SIGMA_105MM-MACRO-LENS-_-F1.4.jpg",
    specs: ["Pro Studio Gear"],
    description: "Technical Specifications: Type: Macro lens Focal Length: 105mm ideal for macro Aperture: F1.4 extremely wide Mount: Sony E-mount native Magnification: 1:1 ma...",
  },
  {
    id: "sigma-70-200mm-f2-8",
    name: "SIGMA 70-200MM / F2.8",
    category: "cameras",
    categoryLabel: "Production Gear",
    dailyRate: 175.0,
    securityDeposit: 262,
    image: "/images/gear/catalog/SIGMA_70-200MM-_-F2.8.jpg",
    specs: ["Pro Studio Gear"],
    description: "Technical Specifications: Type: Telephoto zoom Focal Length: 70-200mm Aperture: Constant F2.8 Mount: Sony E-mount Zoom Ratio: 2.86x Stabilization: Optical fo...",
  },
  {
    id: "sigma-16mm-crop-frame-f1-4",
    name: "SIGMA 16MM CROP FRAME / F1.4",
    category: "cameras",
    categoryLabel: "Production Gear",
    dailyRate: 350.0,
    securityDeposit: 525,
    image: "/images/gear/catalog/SIGMA_16MM-CROP-FRAME-_-F1.4.jpg",
    specs: ["Pro Studio Gear"],
    description: "Technical Specifications: Type: Wide-angle prime APS-C Focal Length: 16mm (24mm equiv FF) Aperture: F1.4 extremely wide Mount: Sony E-mount APS-C Minimum Foc...",
  },
  {
    id: "sony-24-70mm-f2-8-g-master",
    name: "SONY 24-70MM / F2.8 G MASTER",
    category: "cameras",
    categoryLabel: "Production Gear",
    dailyRate: 145.0,
    securityDeposit: 218,
    image: "/images/gear/catalog/SONY_24-70MM-_-F2.8-G-MASTER.jpg",
    specs: ["Pro Studio Gear"],
    description: "Technical Specifications: Type: Professional zoom Focal Length: 24-70mm versatile Aperture: Constant F2.8 Mount: Sony E-mount full-frame Zoom Ratio: 2.9x Sta...",
  },
  {
    id: "canon-70-300mm-f5-6",
    name: "CANON 70-300MM / F5.6",
    category: "cameras",
    categoryLabel: "Production Gear",
    dailyRate: 350.0,
    securityDeposit: 525,
    image: "/images/gear/catalog/CANON_70-300MM-_-F5.6.jpg",
    specs: ["Pro Studio Gear"],
    description: "Technical Specifications: Type: Telephoto zoom Focal Length: 70-300mm Aperture: F5.6 variable Mount: Canon EF mount Zoom Ratio: 4.3x Stabilization: Canon opt...",
  },
  {
    id: "canon-50mm-f1-4",
    name: "CANON 50MM / F1.4",
    category: "cameras",
    categoryLabel: "Production Gear",
    dailyRate: 50.0,
    securityDeposit: 75,
    image: "/images/gear/catalog/CANON_50MM-_-F1.4.jpg",
    specs: ["Pro Studio Gear"],
    description: "Technical Specifications: Type: Prime lens Focal Length: 50mm classic fast Aperture: F1.4 wide Mount: Canon EF mount Minimum Focus: 0.45 meters Aperture Cont...",
  },
  {
    id: "kf-nano-x-black-diffusion-1-2-82mm",
    name: "K&F NANO X BLACK DIFFUSION 1/2 82MM",
    category: "cameras",
    categoryLabel: "Production Gear",
    dailyRate: 40.0,
    securityDeposit: 60,
    image: "/images/gear/catalog/KF_NANO-X-BLACK-DIFFUSION-1_2-82MM.jpg",
    specs: ["Pro Studio Gear"],
    description: "Technical Specifications: Type: Diffusion filter Size: 82mm Strength: 1/2 diffusion moderate Material: Optical glass Coating: Nano anti-reflection Effect: So...",
  },
  {
    id: "kf-nano-d-variable-nd-2-32-cpl-82mm",
    name: "K&F NANO D VARIABLE ND 2-32 & CPL 82MM",
    category: "cameras",
    categoryLabel: "Production Gear",
    dailyRate: 350.0,
    securityDeposit: 525,
    image: "/images/gear/catalog/KF_NANO-D-VARIABLE-ND-2-32-CPL-82MM.jpg",
    specs: ["Pro Studio Gear"],
    description: "Technical Specifications: Type: Variable ND + CPL combo Size: 82mm ND Range: 2-32 stops adjustable CPL Function: Circular polarizer integrated Rotation: 360-...",
  },
  {
    id: "walking-way-blur-point-prism-filter-82mm",
    name: "WALKING WAY BLUR POINT PRISM FILTER 82MM",
    category: "lenses",
    categoryLabel: "Cinema Lens",
    dailyRate: 99.0,
    securityDeposit: 148,
    image: "/images/gear/catalog/WALKING-WAY_BLUR-POINT-PRISM-FILTER-82MM.jpg",
    specs: ["Pro Studio Gear"],
    description: "Technical Specifications: Type: Creative prism filter Size: 82mm Effect: Blur point prism effect Material: Optical glass Coating: Anti-reflection Effect Type...",
  },
  {
    id: "walking-way-filter-mist-1-8-82mm",
    name: "WALKING WAY FILTER MIST 1/8 82MM",
    category: "lenses",
    categoryLabel: "Cinema Lens",
    dailyRate: 100.0,
    securityDeposit: 150,
    image: "/images/gear/catalog/WALKING-WAY_FILTER-MIST-1_8-82MM.jpg",
    specs: ["Pro Studio Gear"],
    description: "Technical Specifications: Type: Mist diffusion filter Size: 82mm Strength: 1/8 mist subtle Material: Optical glass Coating: Anti-reflection Effect: Subtle ci...",
  },
  {
    id: "walking-way-filter-mist-1-4-82mm",
    name: "WALKING WAY FILTER MIST 1/4 82MM",
    category: "lenses",
    categoryLabel: "Cinema Lens",
    dailyRate: 101.0,
    securityDeposit: 152,
    image: "/images/gear/catalog/WALKING-WAY_FILTER-MIST-1_4-82MM.jpg",
    specs: ["Pro Studio Gear"],
    description: "Technical Specifications: Type: Mist diffusion filter Size: 82mm Strength: 1/4 mist moderate Material: Optical glass Coating: Anti-reflection Effect: Visible...",
  },
  {
    id: "puyi-8-star-light-filter-82mm",
    name: "PUYI 8 STAR LIGHT FILTER 82MM",
    category: "lenses",
    categoryLabel: "Cinema Lens",
    dailyRate: 180.0,
    securityDeposit: 270,
    image: "/images/gear/catalog/PUYI_8-STAR-LIGHT-FILTER-82MM.jpg",
    specs: ["Pro Studio Gear"],
    description: "Technical Specifications: Type: Star effect filter Size: 82mm Star Points: 8-pointed Effect: Creates star bursts on lights Material: Optical glass Coating: A...",
  },
  {
    id: "puyi-6-star-light-filter-82mm",
    name: "PUYI 6 STAR LIGHT FILTER 82MM",
    category: "lenses",
    categoryLabel: "Cinema Lens",
    dailyRate: 180.0,
    securityDeposit: 270,
    image: "/images/gear/catalog/PUYI_6-STAR-LIGHT-FILTER-82MM.jpg",
    specs: ["Pro Studio Gear"],
    description: "Technical Specifications: Type: Star effect filter Size: 82mm Star Points: 6-pointed Effect: Classic 6-point star bursts Material: Optical glass Coating: Ant...",
  },
  {
    id: "puyi-4-star-light-filter-82mm",
    name: "PUYI 4 STAR LIGHT FILTER 82MM",
    category: "lenses",
    categoryLabel: "Cinema Lens",
    dailyRate: 180.0,
    securityDeposit: 270,
    image: "/images/gear/catalog/PUYI_4-STAR-LIGHT-FILTER-82MM.jpg",
    specs: ["Pro Studio Gear"],
    description: "Technical Specifications: Type: Star effect filter Size: 82mm Star Points: 4-pointed cross Effect: Simple cross-shaped bursts Material: Optical glass Coating...",
  },
  {
    id: "ewinner-1-2-4-10-lens-set-filters-close-up-62mm",
    name: "eWINNER +1/+2/+4/+10 LENS SET FILTERS CLOSE UP 62MM",
    category: "lenses",
    categoryLabel: "Cinema Lens",
    dailyRate: 180.0,
    securityDeposit: 270,
    image: "/images/gear/catalog/eWINNER_1_2_4_10-LENS-SET-FILTERS-CLOSE-UP-62MM.jpg",
    specs: ["Pro Studio Gear"],
    description: "Technical Specifications: Type: Close-up lens filter set Size: 62mm Strengths: +1, +2, +4, +10 four powers Material: Optical glass Coating: Anti-reflection U...",
  },
  {
    id: "puyi-2-half-prism-filter-82mm",
    name: "PUYI 2 HALF PRISM FILTER 82MM",
    category: "lenses",
    categoryLabel: "Cinema Lens",
    dailyRate: 180.0,
    securityDeposit: 270,
    image: "/images/gear/cooke-s4i-set.jpg",
    specs: ["Pro Studio Gear"],
    description: "Technical Specifications: Type: Half prism effect Size: 82mm Coverage: 50% filter half-frame Effect: Prismatic split-screen Material: Optical glass Coating: ...",
  },
  {
    id: "puyi-2-half-prism-filter-77mm",
    name: "PUYI 2 HALF PRISM FILTER 77MM",
    category: "lenses",
    categoryLabel: "Cinema Lens",
    dailyRate: 180.0,
    securityDeposit: 270,
    image: "/images/gear/cooke-s4i-set.jpg",
    specs: ["Pro Studio Gear"],
    description: "Technical Specifications: Type: Half prism effect Size: 77mm Coverage: 50% half-frame Effect: Prismatic separation Material: Optical glass Coating: Anti-refl...",
  },
  {
    id: "caye-pointer-focus-diffusion-filter-77mm",
    name: "CAYE POINTER FOCUS DIFFUSION FILTER 77MM",
    category: "lenses",
    categoryLabel: "Cinema Lens",
    dailyRate: 180.0,
    securityDeposit: 270,
    image: "/images/gear/cooke-s4i-set.jpg",
    specs: ["Pro Studio Gear"],
    description: "Technical Specifications: Type: Point focus diffusion Size: 77mm Effect: Center sharp, peripheral soft Design: Graduated diffusion Material: Optical glass Co...",
  },
  {
    id: "caye-pointer-focus-diffusion-filter-82mm",
    name: "CAYE POINTER FOCUS DIFFUSION FILTER 82MM",
    category: "lenses",
    categoryLabel: "Cinema Lens",
    dailyRate: 180.0,
    securityDeposit: 270,
    image: "/images/gear/cooke-s4i-set.jpg",
    specs: ["Pro Studio Gear"],
    description: "Technical Specifications: Type: Point focus diffusion Size: 82mm Effect: Center sharp with gradient Design: Graduated from center Material: Optical glass Coa...",
  },
  {
    id: "puyi-half-prism-filter-82mm",
    name: "PUYI HALF PRISM FILTER 82MM",
    category: "lenses",
    categoryLabel: "Cinema Lens",
    dailyRate: 180.0,
    securityDeposit: 270,
    image: "/images/gear/cooke-s4i-set.jpg",
    specs: ["Pro Studio Gear"],
    description: "Technical Specifications: Type: Half prism effect Size: 82mm Coverage: 50% half-frame Effect: Prismatic light refraction Material: Optical glass Coating: Ant...",
  },
  {
    id: "puyi-bold-half-prism-filter-77mm",
    name: "PUYI BOLD HALF PRISM FILTER 77MM",
    category: "lenses",
    categoryLabel: "Cinema Lens",
    dailyRate: 180.0,
    securityDeposit: 270,
    image: "/images/gear/cooke-s4i-set.jpg",
    specs: ["Pro Studio Gear"],
    description: "Technical Specifications: Type: Bold half prism effect Size: 77mm Coverage: Half-frame bold Effect: Stronger prismatic effect Material: Optical glass Coating...",
  },
  {
    id: "generic-transparent-2-5mm-jack-headset",
    name: "Generic Transparent 2.5mm Jack Headset",
    category: "cameras",
    categoryLabel: "Production Gear",
    dailyRate: 350.0,
    securityDeposit: 525,
    image: "/images/gear/catalog/Generic_Transparent-2.5mm-jack-headset.jpg",
    specs: ["Pro Studio Gear"],
    description: "Technical Specifications: Type: Headset with microphone Connector: 2.5mm jack Microphone: Built-in boom mic Features: Hands-free communication Build: Clear t...",
  },
  {
    id: "generic-3-5-neck-mics",
    name: "Generic 3.5 Neck Mics",
    category: "audio",
    categoryLabel: "Pro Audio",
    dailyRate: 95.0,
    securityDeposit: 142,
    image: "/images/gear/catalog/Generic_3.5-Neck-mics.jpg",
    specs: ["Pro Studio Gear"],
    description: "Technical Specifications: Type: Neck-mounted microphone Connector: 3.5mm jack Mounting: Neck-mounted necklace style Microphone: Omnidirectional capsule Build...",
  },
  {
    id: "energizer-aux-cable-3-5-to-3-5",
    name: "Energizer Aux Cable 3.5 to 3.5",
    category: "audio",
    categoryLabel: "Pro Audio",
    dailyRate: 95.0,
    securityDeposit: 142,
    image: "/images/gear/catalog/Energizer_AUX-Cable-3.5.jpg",
    specs: ["Pro Studio Gear"],
    description: "Technical Specifications: Type: Audio cable adapter Connectors: 3.5mm to 3.5mm jack Cable Length: Standard (typically 1-3 meters) Shielding: Professional aud...",
  },
  {
    id: "generic-aux-cable-3-5-to-3-5",
    name: "Generic Aux Cable 3.5 to 3.5",
    category: "audio",
    categoryLabel: "Pro Audio",
    dailyRate: 95.0,
    securityDeposit: 142,
    image: "/images/gear/sennheiser-mkh416-kit.jpg",
    specs: ["Pro Studio Gear"],
    description: "Technical Specifications: Type: Audio cable adapter Style: Curly/spiral wire design Connectors: 3.5mm to 3.5mm Length: Compact coiled length Build: Flexible ...",
  },
  {
    id: "generic-xlr-male-to-aux-male-30-cm",
    name: "Generic XLR Male To Aux Male 30 CM",
    category: "audio",
    categoryLabel: "Pro Audio",
    dailyRate: 95.0,
    securityDeposit: 142,
    image: "/images/gear/catalog/Generic_XLR-Male-To-Aux-male-30-CM.jpg",
    specs: ["Pro Studio Gear"],
    description: "Technical Specifications: Type: Audio adapter cable Length: 30 centimeters compact Connectors: XLR male to 3.5mm male Shield: Professional audio shielding Bu...",
  },
  {
    id: "vention-xlr-male-to-xlr-female-10-meter",
    name: "Vention XLR Male to XLR Female 10 Meter",
    category: "audio",
    categoryLabel: "Pro Audio",
    dailyRate: 95.0,
    securityDeposit: 142,
    image: "/images/gear/catalog/Vention_XLR-male-to-XLR-Female-10-Meter.jpg",
    specs: ["Pro Studio Gear"],
    description: "Technical Specifications: Type: Professional XLR audio cable Length: 10 meters long Connectors: XLR male to XLR female Impedance: 50-70 ohm professional Shie...",
  },
  {
    id: "red-dragon-h260-rgb-headset-usb-port",
    name: "Red Dragon H260 RGB Headset USB Port",
    category: "cameras",
    categoryLabel: "Cinema Camera",
    dailyRate: 350.0,
    securityDeposit: 525,
    image: "/images/gear/catalog/Red-Dragon_H260-RGB-Headset-USB-Port.jpg",
    specs: ["Pro Studio Gear"],
    description: "Technical Specifications: Type: Gaming headset with RGB Connection: USB port RGB: Light-up capability Audio: 7.1 surround sound capable Build: Professional g...",
  },
  {
    id: "amazon-box-weatherproof-22-x-14-x-10-inch",
    name: "AMAZON BOX Weatherproof 22 x 14 x 10 Inch",
    category: "cameras",
    categoryLabel: "Production Gear",
    dailyRate: 200.0,
    securityDeposit: 300,
    image: "/images/gear/arri-alexa-mini-lf.jpg",
    specs: ["Pro Studio Gear"],
    description: "Technical Specifications: Type: Weatherproof hard case Dimensions: 22 x 14 x 10 inches Material: Heavy-duty plastic Features: Water resistant, durable constr...",
  },
  {
    id: "fusion-rig-for-sony-fx3-cinema-cage",
    name: "FUSION RIG For Sony FX3 Cinema Cage",
    category: "cameras",
    categoryLabel: "Cinema Camera",
    dailyRate: 200.0,
    securityDeposit: 300,
    image: "/images/gear/catalog/FUSION-RIG_FOR-SONY-FX3-CINEMA-CAGE.jpg",
    specs: ["Pro Studio Gear"],
    description: "Technical Specifications: Type: Professional cinema rig system Compatibility: Sony FX3 cameras Components: Complete mounting system Material: Professional al...",
  },
  {
    id: "tilta-ff-t06-manual-follow-focus",
    name: "TILTA FF-T06 Manual Follow Focus",
    category: "cameras",
    categoryLabel: "Production Gear",
    dailyRate: 200.0,
    securityDeposit: 300,
    image: "/images/gear/catalog/TILTA_FF-T06-MANUAL-FOLLOW-FOCUS.jpg",
    specs: ["Pro Studio Gear"],
    description: "Technical Specifications: Type: Professional manual follow focus system Features: Manual focus control Build: Precision machined aluminum Mounting: 15mm rod ...",
  },
  {
    id: "tilta-black-leather-side-handle",
    name: "TILTA BLACK LEATHER SIDE HANDLE",
    category: "cameras",
    categoryLabel: "Production Gear",
    dailyRate: 200.0,
    securityDeposit: 300,
    image: "/images/gear/catalog/TILTA_BLACK-LEATHER-SIDE-HANDLE.jpg",
    specs: ["Pro Studio Gear"],
    description: "Technical Specifications: Type: Professional side handle grip Material: Black leather construction Mounting: 15mm rod compatible Ergonomics: Comfortable prof...",
  },
  {
    id: "tilta-camera-baseplate-15mm-lws",
    name: "TILTA CAMERA BASEPLATE 15MM LWS",
    category: "cameras",
    categoryLabel: "Cinema Camera",
    dailyRate: 200.0,
    securityDeposit: 300,
    image: "/images/gear/catalog/TILTA_CAMERA-BASEPLATE-15MM-LWS.jpg",
    specs: ["Pro Studio Gear"],
    description: "Technical Specifications: Type: Professional camera baseplate Rod Size: 15mm lightweight system Build: Precision machined aluminum Mounting: Universal camera...",
  },
  {
    id: "tilta-v-mount-battery-plate-v2",
    name: "TILTA V MOUNT BATTERY PLATE V2",
    category: "cameras",
    categoryLabel: "Production Gear",
    dailyRate: 350.0,
    securityDeposit: 525,
    image: "/images/gear/catalog/TILTA_V-MOUNT-BATTERY-PLATE-V2.jpg",
    specs: ["Pro Studio Gear"],
    description: "Technical Specifications: Type: V-Mount battery plate system Version: V2 upgraded model Build: Professional aluminum construction Compatibility: V-Mount cine...",
  },
  {
    id: "smallrig-npf-battery-adapter-plate",
    name: "SMALLRIG NPF BATTERY ADAPTER PLATE",
    category: "cameras",
    categoryLabel: "Production Gear",
    dailyRate: 350.0,
    securityDeposit: 525,
    image: "/images/gear/catalog/SMALLRIG_NPF-BATTERY-ADAPTER-PLATE.jpg",
    specs: ["Pro Studio Gear"],
    description: "Technical Specifications: Type: NPF battery mounting plate Compatibility: NP-F series batteries Build: Professional aluminum Mounting: Rig compatible Feature...",
  },
  {
    id: "smallrig-two-handles",
    name: "SMALLRIG TWO HANDLES",
    category: "cameras",
    categoryLabel: "Production Gear",
    dailyRate: 350.0,
    securityDeposit: 525,
    image: "/images/gear/arri-alexa-mini-lf.jpg",
    specs: ["Pro Studio Gear"],
    description: "Technical Specifications: Type: Professional dual handles Build: Aluminum construction Mounting: Universal rail compatible Ergonomics: Comfortable grip desig...",
  },
  {
    id: "smallrig-shollder-plate",
    name: "SMALLRIG SHOLLDER PLATE",
    category: "cameras",
    categoryLabel: "Production Gear",
    dailyRate: 350.0,
    securityDeposit: 525,
    image: "/images/gear/catalog/SMALLRIG_SHOULDER-PLATE.jpg",
    specs: ["Pro Studio Gear"],
    description: "Technical Specifications: Type: Professional shoulder support plate Build: Heavy-duty aluminum Mounting: 15mm rod compatible Ergonomics: Shoulder-mounted ope...",
  },
  {
    id: "smallrig-npfz100-dummy-battery-to-d-tap",
    name: "SMALLRIG NPFZ100 DUMMY BATTERY TO D TAP",
    category: "cameras",
    categoryLabel: "Production Gear",
    dailyRate: 350.0,
    securityDeposit: 525,
    image: "/images/gear/catalog/SMALLRIG_NPFZ100-DUMMY-BATTERY-TO-D-TAP.jpg",
    specs: ["Pro Studio Gear"],
    description: "Technical Specifications: Type: Power adapter system Input: NPFZ100 battery dummy Output: D-Tap professional connector Function: Battery power conversion Bui...",
  },
  {
    id: "ulanzi-usb-c-cooler-fan-for-fx3",
    name: "ULANZI USB C COOLER FAN FOR FX3",
    category: "cameras",
    categoryLabel: "Cinema Camera",
    dailyRate: 350.0,
    securityDeposit: 525,
    image: "/images/gear/catalog/ULANZI_USB-C-COOLER-FAN-FOR-FX3.jpg",
    specs: ["Pro Studio Gear"],
    description: "Technical Specifications: Type: Cooling fan system Compatibility: Sony FX3 cameras Power: USB-C powered Function: Heat management for extended recording Buil...",
  },
  {
    id: "x2-40-cm-rod",
    name: "X2 40 CM ROD",
    category: "cameras",
    categoryLabel: "Production Gear",
    dailyRate: 350.0,
    securityDeposit: 525,
    image: "/images/gear/arri-alexa-mini-lf.jpg",
    specs: ["Pro Studio Gear"],
    description: "Technical Specifications: Type: Carbon fiber support rod Length: 40 centimeters Material: Carbon fiber lightweight Diameter: Standard 15mm compatible Build: ...",
  },
  {
    id: "x2-30-cm-rod",
    name: "X2 30 CM ROD",
    category: "cameras",
    categoryLabel: "Production Gear",
    dailyRate: 350.0,
    securityDeposit: 525,
    image: "/images/gear/arri-alexa-mini-lf.jpg",
    specs: ["Pro Studio Gear"],
    description: "Technical Specifications: Type: Metal support rod system Length: 30 centimeters Material: Aluminum alloy metal Diameter: Standard small rig compatible Build:...",
  },
  {
    id: "x2-20-cm-rod",
    name: "X2 20 CM ROD",
    category: "cameras",
    categoryLabel: "Production Gear",
    dailyRate: 350.0,
    securityDeposit: 525,
    image: "/images/gear/arri-alexa-mini-lf.jpg",
    specs: ["Pro Studio Gear"],
    description: "Technical Specifications: Type: Metal support rod system Length: 20 centimeters Material: Aluminum alloy metal Diameter: Standard small rig compatible Build:...",
  },
  {
    id: "white-balanceitem-white-balance-color-correction",
    name: "WHITE BALANCEITEM WHITE BALANCE - Color Correction",
    category: "cameras",
    categoryLabel: "Production Gear",
    dailyRate: 200.0,
    securityDeposit: 300,
    image: "/images/gear/arri-alexa-mini-lf.jpg",
    specs: ["Pro Studio Gear"],
    description: "Technical Specifications: Type: White balance reference chart Color: Gray reference card Material: Plastic construction Purpose: Color correction in post-pro...",
  },
  {
    id: "sony-cinema-line-fx3-ilme-2",
    name: "Sony Cinema Line FX3 ILME",
    category: "cameras",
    categoryLabel: "Cinema Camera",
    dailyRate: 350.0,
    securityDeposit: 525,
    image: "/images/gear/catalog/Sony-Cinema-Line-FX3-ILME-2.jpg",
    specs: ["Pro Studio Gear"],
    description: "أهم المواصفات الفنية: - نوع المستشعر: Full-Frame مقاس 35mm (35.6 x 23.8mm) من نوع Exmor R CMOS بإضاءة خلفية - عدد البكسلات الفعلي: 12.1 ميجابكسل (للصور)، 10....",
  },
  {
    id: "sony-fdr-ax100e-with-cage-top-handle-2",
    name: "Sony FDR-AX100E (with Cage & Top Handle)",
    category: "cameras",
    categoryLabel: "Cinema Camera",
    dailyRate: 350.0,
    securityDeposit: 525,
    image: "/images/gear/catalog/Sony-FDR-AX100E-with-Cage-Top-Handle.jpg",
    specs: ["Pro Studio Gear"],
    description: "أهم المواصفات الفنية: - نوع المستشعر: Exmor R CMOS مقاس 1.0 بوصة (13.2 x 8.8mm) بإضاءة خلفية - عدد البكسلات الفعلي: 14.2 ميجابكسل (16:9) - معالج الصور: BIONZ...",
  },
  {
    id: "sony-alpha-a6500-ilce-2",
    name: "Sony Alpha A6500 ILCE",
    category: "cameras",
    categoryLabel: "Cinema Camera",
    dailyRate: 350.0,
    securityDeposit: 525,
    image: "/images/gear/catalog/Sony-Alpha-A6500-ILCE.jpg",
    specs: ["Pro Studio Gear"],
    description: "أهم المواصفات الفنية: - نوع المستشعر: CMOS بحجم APS-C (23.8 x 15.9mm) - عدد البكسلات الفعلي: 24.2 ميجابكسل - معالج الصور: BIONZ X - التصوير المتتابع: 11 إطار...",
  },
  {
    id: "dji-osmo-pocket-3-2",
    name: "DJI OSMO Pocket 3",
    category: "cameras",
    categoryLabel: "Cinema Camera",
    dailyRate: 120.0,
    securityDeposit: 180,
    image: "/images/gear/catalog/DJI-OSMO-Pocket-3.jpg",
    specs: ["Pro Studio Gear"],
    description: "أهم المواصفات الفنية: - نوع المستشعر: CMOS مقاس 1 بوصة (قطر 16mm) - العدسة: 20mm f/2.0 (ما يعادل 35mm) - دقة الفيديو: 4K حتى 120fps (نسبة 16:9)، 3K حتى 120fp...",
  },
  {
    id: "dji-mini-3-pro-combo-2",
    name: "DJI Mini 3 Pro Combo",
    category: "bundles",
    categoryLabel: "Turnkey Kit",
    dailyRate: 300.0,
    securityDeposit: 450,
    image: "/images/gear/catalog/DJI-Mini-3-Pro-Combo-2.jpg",
    specs: ["Pro Studio Gear"],
    isKit: true,
    includedInKit: ["DJI Mini 3 Pro 4K Drone", "DJI RC Controller with FHD Display", "3x Intelligent Flight Batteries", "Two-Way Battery Charging Hub", "Shoulder Carry Bag", "Spare Low-Noise Propellers"],
    description: "أهم المواصفات الفنية: - الوزن: 249g (خفيف جدًا - معفى من التسجيل في معظم المناطق) - مستشعر الكاميرا: CMOS مقاس 1/2 بوصة، 12 ميجابكسل - دقة الفيديو: 4K عند 60...",
  },
  {
    id: "dji-mavic-air-2-combo-2",
    name: "DJI Mavic Air 2 Combo",
    category: "bundles",
    categoryLabel: "Turnkey Kit",
    dailyRate: 300.0,
    securityDeposit: 450,
    image: "/images/gear/catalog/DJI-Mavic-Air-2-Combo.jpg",
    specs: ["Pro Studio Gear"],
    isKit: true,
    includedInKit: ["Turnkey Production Unit", "Accessories & Cabling", "Protective Case"],
    description: "أهم المواصفات الفنية: - مستشعر الكاميرا: CMOS بحجم 4/3 (حجم أكبر لجودة صورة أعلى) - دقة الفيديو: 4K عند 60fps (UHD 3840 x 2160)، و1080p عند 240fps (تصوير بال...",
  },
  {
    id: "insta360-x3-combo-kit-2",
    name: "INSTA360 X3 Combo Kit",
    category: "cameras",
    categoryLabel: "Cinema Camera",
    dailyRate: 75.0,
    securityDeposit: 112,
    image: "/images/gear/catalog/INSTA360-X3-Combo-Kit.jpg",
    specs: ["Pro Studio Gear"],
    description: "أهم المواصفات الفنية: - دقة الفيديو: فيديو كروي 360 درجة بدقة 5.7K (5760 x 2880) - معدل الإطارات: 5.7K عند 24/25/30fps مع Active HDR - أقصى معدل بت: 130 Mbps...",
  },
  {
    id: "insta360-sphere-4h5asq-2",
    name: "INSTA360 Sphere 4H5ASQ",
    category: "cameras",
    categoryLabel: "Cinema Camera",
    dailyRate: 350.0,
    securityDeposit: 525,
    image: "/images/gear/catalog/INSTA360-Sphere-2.jpg",
    specs: ["Pro Studio Gear"],
    description: "أهم المواصفات: - النوع: نظام كاميرا كروية 360 درجة منفصل يُركّب على الدرون - الدقة: 5760x2880 عند 30/25/24fps | 3840x1920 عند 50/30fps | 3008x1504 عند 100fps...",
  },
  {
    id: "sony-npfz100-for-fx3-2",
    name: "Sony NPFZ100 FOR FX3",
    category: "cameras",
    categoryLabel: "Cinema Camera",
    dailyRate: 10.0,
    securityDeposit: 15,
    image: "/images/gear/catalog/Sony-NPFZ100-FOR-FX3.jpg",
    specs: ["Pro Studio Gear"],
    description: "المواصفات الفنية: الجهد: 7.7V اسمي | السعة: 2100mAh (16.2Wh) | نوع الخلايا: ليثيوم أيون | التوافق: Sony FX3 وFX30 وA1 | مدة الشحن: 150 دقيقة | عمر البطارية: ...",
  },
  {
    id: "power-extra-npfz100-for-fx3-2",
    name: "Power Extra NPFZ100 FOR FX3",
    category: "cameras",
    categoryLabel: "Cinema Camera",
    dailyRate: 10.0,
    securityDeposit: 15,
    image: "/images/gear/catalog/Power-Extra-NPFZ100-FOR-FX3.jpg",
    specs: ["Pro Studio Gear"],
    description: "المواصفات الفنية: الجهد: 7.7V اسمي | السعة: 2100mAh (16.2Wh) | نوع الخلايا: ليثيوم أيون | التوافق: Sony FX3 وFX30 وA1 | مدة الشحن: من 120 إلى 150 دقيقة | عمر...",
  },
  {
    id: "enegon-npfz100-for-fx3-2",
    name: "ENEGON NPFZ100 FOR FX3",
    category: "cameras",
    categoryLabel: "Cinema Camera",
    dailyRate: 10.0,
    securityDeposit: 15,
    image: "/images/gear/catalog/ENEGON-NPFZ100-FOR-FX3-1.jpg",
    specs: ["Pro Studio Gear"],
    description: "المواصفات الفنية: الجهد: 7.7V اسمي | السعة: 2100mAh (16.2Wh) | نوع الخلايا: ليثيوم أيون | التوافق: Sony FX3 وFX30 وA1 | مدة الشحن: 150 دقيقة | عمر البطارية: ...",
  },
  {
    id: "sony-single-npfz100-charger-2",
    name: "Sony SINGLE NPFZ100 Charger",
    category: "cameras",
    categoryLabel: "Production Gear",
    dailyRate: 15.0,
    securityDeposit: 22,
    image: "/images/gear/catalog/Sony-SINGLE-NPFZ100-Charger-2.jpg",
    specs: ["Pro Studio Gear"],
    description: "المواصفات الفنية: الدخل: AC 100-240V، 50/60Hz | الخرج: 8.4V، 1.6A | مدة الشحن: 150 دقيقة | البطاريات المتوافقة: NPFZ100 | المميزات: شحن ذكي، مؤشر للشحن | الأ...",
  },
  {
    id: "power-extra-dual-usb-npfz100-charger-2",
    name: "Power Extra Dual USB NPFZ100 Charger",
    category: "cameras",
    categoryLabel: "Production Gear",
    dailyRate: 25.0,
    securityDeposit: 38,
    image: "/images/gear/catalog/Power-Extra-Dual-USB-NPFZ100-Charger.jpg",
    specs: ["Pro Studio Gear"],
    description: "المواصفات الفنية: النوع: منفذا شحن مزدوجان | الدخل: USB Power Delivery (يُنصح بـ 18W) | الشحن المتزامن: 2x NPFZ100 | مدة الشحن: 150 دقيقة لكل بطارية | المميز...",
  },
  {
    id: "power-extra-dual-usb-npfw50-charger-2",
    name: "Power Extra Dual USB NPFW50 Charger",
    category: "cameras",
    categoryLabel: "Production Gear",
    dailyRate: 350.0,
    securityDeposit: 525,
    image: "/images/gear/catalog/Power-Extra-Dual-USB-NPFW50-Charger.jpg",
    specs: ["Pro Studio Gear"],
    description: "المواصفات الفنية: النوع: منفذا شحن مزدوجان | الدخل: USB Power Delivery (بحد أدنى 12W) | الشحن المتزامن: 2x NPFW50 | مدة الشحن: 120 دقيقة لكل بطارية | المميزا...",
  },
  {
    id: "power-extra-npfw50-2",
    name: "Power Extra NPFW50",
    category: "cameras",
    categoryLabel: "Production Gear",
    dailyRate: 350.0,
    securityDeposit: 525,
    image: "/images/gear/catalog/Power-Extra-Dual-USB-NPFW50-Charger.jpg",
    specs: ["Pro Studio Gear"],
    description: "المواصفات الفنية: الجهد: 7.7V اسمي | السعة: 1680mAh (12.9Wh) | نوع الخلايا: ليثيوم أيون | التوافق: سلسلة Sony FX | مدة الشحن: 120 دقيقة | عمر البطارية: أكثر ...",
  },
  {
    id: "tilta-fx3-cage-2",
    name: "TILTA FX3 CAGE",
    category: "cameras",
    categoryLabel: "Cinema Camera",
    dailyRate: 350.0,
    securityDeposit: 525,
    image: "/images/gear/arri-alexa-mini-lf.jpg",
    specs: ["Pro Studio Gear"],
    description: "المواصفات الفنية: الخامة: سبيكة ألومنيوم | الوزن: من 400 إلى 500g للقفص | التركيب: متوافق مع NATO rail | دعم القضبان: 15mm | المميزات: قاعدة لتركيب المقبض ال...",
  },
  {
    id: "sony-npfv70-2",
    name: "Sony NPFV70",
    category: "cameras",
    categoryLabel: "Production Gear",
    dailyRate: 350.0,
    securityDeposit: 525,
    image: "/images/gear/catalog/Sony-NPFV70.jpg",
    specs: ["Pro Studio Gear"],
    description: "المواصفات الفنية: الجهد: 7.2V اسمي | السعة: 2100mAh (15.1Wh) | نوع الخلايا: ليثيوم أيون | التوافق: Sony AX100 وAX33 وسلسلة HXR | مدة الشحن: 130 دقيقة | عمر ا...",
  },
  {
    id: "newell-npfv100-a-2",
    name: "NEWELL NPFV100 A",
    category: "cameras",
    categoryLabel: "Production Gear",
    dailyRate: 350.0,
    securityDeposit: 525,
    image: "/images/gear/catalog/NEWELL-NPFV100-A.jpg",
    specs: ["Pro Studio Gear"],
    description: "المواصفات الفنية: الجهد: 7.4V اسمي | السعة: 2700mAh (19.98Wh) | نوع الخلايا: ليثيوم أيون | التوافق: كاميرات Sony AX100 وAX33 وHXR | مدة الشحن: 150 دقيقة | عم...",
  },
  {
    id: "li-ion-battery-npfv100-a",
    name: "LI ION BATTERY NPFV100 A",
    category: "cameras",
    categoryLabel: "Production Gear",
    dailyRate: 350.0,
    securityDeposit: 525,
    image: "/images/gear/arri-alexa-mini-lf.jpg",
    specs: ["Pro Studio Gear"],
    description: "المواصفات الفنية: الجهد: 7.4V اسمي | السعة: 2700mAh (19.98Wh) | نوع الخلايا: ليثيوم أيون | التوافق: Sony AX100 وAX33 وسلسلة HXR | مدة الشحن: 150 دقيقة | عمر ...",
  },
  {
    id: "ravpower-dual-npfz100-charger-2",
    name: "RAVPOWER Dual NPFZ100 CHARGER",
    category: "cameras",
    categoryLabel: "Production Gear",
    dailyRate: 350.0,
    securityDeposit: 525,
    image: "/images/gear/arri-alexa-mini-lf.jpg",
    specs: ["Pro Studio Gear"],
    description: "المواصفات الفنية: النوع: شاحن بطاريات مزدوج | الدخل: AC 110-240V أو USB | الخرج: منفذا شحن | مدة الشحن: من 120 إلى 150 دقيقة لكل بطارية | البطاريات المتوافقة...",
  },
  {
    id: "enegon-dual-npfz100-charger-2",
    name: "ENEGON Dual NPFZ100 CHARGER",
    category: "cameras",
    categoryLabel: "Production Gear",
    dailyRate: 25.0,
    securityDeposit: 38,
    image: "/images/gear/catalog/ENEGON-NPFZ100-FOR-FX3.jpg",
    specs: ["Pro Studio Gear"],
    description: "المواصفات الفنية: النوع: شاحن بطاريات مزدوج | الدخل: AC 110-240V | الخرج: منفذا شحن | مدة الشحن: 150 دقيقة لكل بطارية | البطاريات المتوافقة: NPFZ100 | المميز...",
  },
  {
    id: "for-npfv-dual-usb-npfv-charger-2",
    name: "FOR NPFV Dual USB NPFV CHARGER",
    category: "cameras",
    categoryLabel: "Production Gear",
    dailyRate: 350.0,
    securityDeposit: 525,
    image: "/images/gear/arri-alexa-mini-lf.jpg",
    specs: ["Pro Studio Gear"],
    description: "المواصفات الفنية: النوع: شحن USB مزدوج | الدخل: USB Power Delivery (بحد أدنى 12W) | الخرج: منفذا شحن | أنواع البطاريات: NPFV70 وNPFV100 | مدة الشحن: من 120 إ...",
  },
  {
    id: "enegon-dual-usb-npf-battery-charger-2",
    name: "ENEGON Dual USB NPF BATTERY CHARGER",
    category: "cameras",
    categoryLabel: "Production Gear",
    dailyRate: 25.0,
    securityDeposit: 38,
    image: "/images/gear/catalog/ENEGON-DUAL-USB-NPF-BATTERY-CHARGER.jpg",
    specs: ["Pro Studio Gear"],
    description: "المواصفات الفنية: النوع: محطة شحن USB مزدوجة | الدخل: USB Power Delivery (يُنصح بـ 18W) | الخرج: منفذا شحن | توافق البطاريات: سلسلة NPF (NP-F970 وNP-F750 وغي...",
  },
  {
    id: "power-extra-dual-usb-npf-battery-charger-2",
    name: "Power Extra Dual USB NPF BATTERY CHARGER",
    category: "cameras",
    categoryLabel: "Production Gear",
    dailyRate: 25.0,
    securityDeposit: 38,
    image: "/images/gear/catalog/Power-Extra-DUAL-USB-NPF-BATTERY-CHARGER.jpg",
    specs: ["Pro Studio Gear"],
    description: "المواصفات الفنية: النوع: شحن USB مزدوج لكل وحدة | الدخل: USB Power Delivery (بحد أدنى 12W) | الخرج: منفذان لكل شاحن (4 منافذ إجمالًا) | توافق البطاريات: سلسل...",
  },
  {
    id: "neweer-dual-usb-npf-battery-charger-2",
    name: "NEWEER Dual USB NPF BATTERY CHARGER",
    category: "cameras",
    categoryLabel: "Production Gear",
    dailyRate: 25.0,
    securityDeposit: 38,
    image: "/images/gear/catalog/NEWEER-NP-F970-_-6600MAH-1.jpg",
    specs: ["Pro Studio Gear"],
    description: "المواصفات الفنية: النوع: شحن USB مزدوج لكل وحدة | الدخل: USB Power Delivery (يُنصح بـ 18W) | الخرج: منفذان لكل شاحن (6 منافذ إجمالًا) | توافق البطاريات: سلسل...",
  },
  {
    id: "neweer-np-f970-6600mah-2",
    name: "NEWEER NP-F970 / 6600MAH",
    category: "cameras",
    categoryLabel: "Production Gear",
    dailyRate: 350.0,
    securityDeposit: 525,
    image: "/images/gear/catalog/NEWEER-NP-F970-_-6600MAH.jpg",
    specs: ["Pro Studio Gear"],
    description: "المواصفات الفنية: الجهد: 7.4V اسمي | السعة: 6600mAh (48.84Wh) | نوع الخلايا: ليثيوم أيون | التوافق: سلسلة Sony PMW وكاميرات الفيديو الاحترافية | مدة الشحن: م...",
  },
  {
    id: "power-extra-np-f970-8800mah-2",
    name: "Power Extra NP-F970 / 8800MAH",
    category: "cameras",
    categoryLabel: "Production Gear",
    dailyRate: 350.0,
    securityDeposit: 525,
    image: "/images/gear/catalog/Power-Extra-NP-F970-_-8800MAH.jpg",
    specs: ["Pro Studio Gear"],
    description: "المواصفات الفنية: الجهد: 7.4V اسمي | السعة: 8800mAh (65.12Wh) | نوع الخلايا: ليثيوم أيون | التوافق: كاميرات فيديو Sony بقاعدة NP-F | مدة الشحن: من 240 إلى 30...",
  },
  {
    id: "power-extra-np-f770-5200mah-2",
    name: "Power Extra NP-F770 / 5200MAH",
    category: "cameras",
    categoryLabel: "Production Gear",
    dailyRate: 350.0,
    securityDeposit: 525,
    image: "/images/gear/catalog/Power-Extra-NP-F970-_-8800MAH.jpg",
    specs: ["Pro Studio Gear"],
    description: "المواصفات الفنية: الجهد: 7.4V اسمي | السعة: 5200mAh (38.48Wh) | نوع الخلايا: ليثيوم أيون | التوافق: كاميرات فيديو Sony الاحترافية | مدة الشحن: من 180 إلى 200...",
  },
  {
    id: "enegon-np-f550-2900mah-2",
    name: "ENEGON NP-F550 / 2900MAH",
    category: "cameras",
    categoryLabel: "Production Gear",
    dailyRate: 350.0,
    securityDeposit: 525,
    image: "/images/gear/catalog/ENEGON-NP-F550-_-2900MAH.jpg",
    specs: ["Pro Studio Gear"],
    description: "المواصفات الفنية: الجهد: 7.4V اسمي | السعة: 2900mAh (21.46Wh) | نوع الخلايا: ليثيوم أيون | التوافق: كاميرات Sony بقاعدة NP-F | مدة الشحن: من 120 إلى 150 دقيق...",
  },
  {
    id: "pro-x-gb2lsj-v-mount-dual-battery-charger-2",
    name: "PRO X GB2LSJ - V MOUNT DUAL BATTERY CHARGER",
    category: "cameras",
    categoryLabel: "Production Gear",
    dailyRate: 40.0,
    securityDeposit: 60,
    image: "/images/gear/catalog/PRO-X-GBL90B-V-MOUNT-BATTERY.jpg",
    specs: ["Pro Studio Gear"],
    description: "المواصفات الفنية: النوع: محطة شحن مزدوجة V-Mount | نوع القاعدة: V-Mount (متوافقة مع Anton Bauer) | سعة الشحن: بطاريتان في نفس الوقت | الدخل: AC 110-240V | ال...",
  },
  {
    id: "pro-x-gbl90b-v-mount-battery-2",
    name: "PRO X GBL90B - V MOUNT BATTERY",
    category: "cameras",
    categoryLabel: "Production Gear",
    dailyRate: 40.0,
    securityDeposit: 60,
    image: "/images/gear/catalog/PRO-X-GBL90B-V-MOUNT-BATTERY.jpg",
    specs: ["Pro Studio Gear"],
    description: "المواصفات الفنية: النوع: بطارية سينمائية V-Mount | الجهد: 14.4V اسمي | السعة: 9000mAh (129.6Wh) | نوع الخلايا: ليثيوم بوليمر | نوع القاعدة: V-Mount | التوافق...",
  },
  {
    id: "innox-in-99s-6875mah-2",
    name: "INNOX IN-99S 6875MAH",
    category: "cameras",
    categoryLabel: "Production Gear",
    dailyRate: 350.0,
    securityDeposit: 525,
    image: "/images/gear/catalog/INNOX_IN-99S-6875mAh.jpg",
    specs: ["Pro Studio Gear"],
    description: "المواصفات الفنية: الجهد: 7.4V اسمي | السعة: 6875mAh (50.875Wh) | نوع الخلايا: ليثيوم أيون | التصميم: تشطيب ألياف كربون | التوافق: كاميرات فيديو Sony الاحتراف...",
  },
  {
    id: "power-extra-station-hub-for-npf-2",
    name: "Power Extra STATION HUB FOR NPF",
    category: "cameras",
    categoryLabel: "Production Gear",
    dailyRate: 350.0,
    securityDeposit: 525,
    image: "/images/gear/catalog/Power-Extra_STATION-HUB-FOR-NPF.jpg",
    specs: ["Pro Studio Gear"],
    description: "المواصفات الفنية: النوع: محطة شحن NPF | سعة الشحن: 4 بطاريات في نفس الوقت | أنواع البطاريات: NP-F970 وNP-F770 وNP-F750 وNP-F550 وغيرها | الدخل: AC 110-240V |...",
  },
  {
    id: "dji-focus-pro-combo-2",
    name: "DJI FOCUS PRO COMBO",
    category: "bundles",
    categoryLabel: "Turnkey Kit",
    dailyRate: 350.0,
    securityDeposit: 525,
    image: "/images/gear/catalog/DJI_FOCUS-PRO-COMBO-2.jpg",
    specs: ["Pro Studio Gear"],
    isKit: true,
    includedInKit: ["DJI LiDAR Sensor Module", "Focus Pro High-Torque Motor", "Focus Pro Ergonomic Grip", "Wireless FIZ Hand Unit", "15mm Rod Mount & Cables", "Custom Hard Case"],
    description: "المواصفات الفنية: النوع: نظام احترافي للتحكم في التركيز | المكونات: موتور، مستشعر LIDAR، مقبض تركيز، ملحقات | التوافق: تجهيزات الكاميرات السينمائية بدعم قضبا...",
  },
  {
    id: "tilta-mirage-matte-box-kit-mb-t16-a-2",
    name: "TILTA MIRAGE MATTE BOX Kit MB-T16-A",
    category: "bundles",
    categoryLabel: "Turnkey Kit",
    dailyRate: 105.0,
    securityDeposit: 158,
    image: "/images/gear/catalog/TILTA_MIRAGE-MATTE-BOX-Kit-MB-T16-A.jpg",
    specs: ["Pro Studio Gear"],
    isKit: true,
    includedInKit: ["Tilta Mirage Ultra-Lightweight Matte Box", "95mm Variable Circular ND Filter", "15mm LWS Single Rod Adapter", "Adapter Rings (67mm, 72mm, 77mm, 82mm)", "Carbon Fiber Top Flag", "Protective Flight Case"],
    description: "المواصفات الفنية: النوع: ماتي بوكس سينمائي احترافي | مقاسات العدسات: يغطي 67mm و72mm و77mm و82mm | التركيب: متوافق مع قضبان 15mm | المكونات: قضيب، ماتي بوكس،...",
  },
  {
    id: "nisi-polarizer-4x5-65-2",
    name: "NISI POLARIZER 4X5.65",
    category: "lenses",
    categoryLabel: "Cinema Lens",
    dailyRate: 180.0,
    securityDeposit: 270,
    image: "/images/gear/catalog/NISI_POLARIZER-4X5.65.jpg",
    specs: ["Pro Studio Gear"],
    description: "المواصفات الفنية: النوع: فلتر بولارايزر احترافي | المقاس: 4x5.65 (المقاس السينمائي القياسي) | التأثير: يزيل الانعكاسات ويبرز الألوان | الخامة: زجاج بصري | ال...",
  },
  {
    id: "tilta-float-dual-handle-gimbal-support-system-2",
    name: "TILTA Float Dual-Handle Gimbal Support System",
    category: "cameras",
    categoryLabel: "Production Gear",
    dailyRate: 350.0,
    securityDeposit: 525,
    image: "/images/gear/arri-alexa-mini-lf.jpg",
    specs: ["Pro Studio Gear"],
    description: "المواصفات الفنية: النوع: نظام دعم للجيمبل بمقبضين | قدرة التحمل: تجهيزات الكاميرات السينمائية الاحترافية | المقابض: مقبضان مريحان لتشغيل سلس | التثبيت: يجعل ...",
  },
  {
    id: "tilta-basic-ring-grip-plus-tgaprg2-2",
    name: "TILTA BASIC RING GRIP PLUS TGAPRG2",
    category: "cameras",
    categoryLabel: "Production Gear",
    dailyRate: 350.0,
    securityDeposit: 525,
    image: "/images/gear/catalog/TILTA_BASIC-RING-GRIP-PLUS-TGAPRG2.jpg",
    specs: ["Pro Studio Gear"],
    description: "المواصفات الفنية: النوع: حلقة تحكم احترافية للتركيز | السطح: سطح إمساك ناعم | الدوران: حركة سلسة لحلقة التركيز | التركيب: متوافق مع قضبان 15mm | التصنيع: ألو...",
  },
  {
    id: "dji-rs-4-pro-combo-gimbal-stabilizer-2",
    name: "DJI RS 4 Pro Combo GIMBAL STABILIZER",
    category: "bundles",
    categoryLabel: "Turnkey Kit",
    dailyRate: 140.0,
    securityDeposit: 210,
    image: "/images/gear/catalog/DJI_RS-4-Pro-Combo-GIMBAL-STABILIZER.jpg",
    specs: ["Pro Studio Gear"],
    isKit: true,
    includedInKit: ["DJI RS 4 Pro Carbon Fiber Gimbal", "Focus Pro Motor & Gear Strip", "Ronin Image Transmitter (RavenEye)", "Briefcase Handle & Extended Grip/Tripod", "Quick-Release Plates (Arca-Swiss/Manfrotto)", "Carrying Case & Multi-Camera Control Cables"],
    description: "المواصفات الفنية: النوع: جيمبل تثبيت احترافي | الحمولة القصوى: كاميرات حتى 3kg | عزم المحرك: محسّن للكاميرات السينمائية الثقيلة | مدة تشغيل البطارية: من 16 إ...",
  },
  {
    id: "dji-rs-2-pro-combo-gimbal-stabilizer-2",
    name: "DJI RS 2 Pro Combo GIMBAL STABILIZER",
    category: "bundles",
    categoryLabel: "Turnkey Kit",
    dailyRate: 120.0,
    securityDeposit: 180,
    image: "/images/gear/catalog/DJI_RS-2-Pro-GIMBAL-STABILIZER.jpg",
    specs: ["Pro Studio Gear"],
    isKit: true,
    includedInKit: ["DJI RS 2 Carbon Fiber Gimbal", "Ronin RavenEye Image Transmitter", "Focus Motor & Rod Mount", "Phone Holder & Briefcase Handle", "Dual-Layer Quick Release Plates", "Water-Resistant Hard Shell Case"],
    description: "المواصفات الفنية: النوع: جيمبل تثبيت احترافي | الحمولة القصوى: حتى 3kg | عزم المحرك: بمستوى احترافي | مدة تشغيل البطارية: من 14 إلى 18 ساعة | التحكم: ريموت ل...",
  },
  {
    id: "dji-rs-2-pro-gimbal-stabilizer-2",
    name: "DJI RS 2 Pro GIMBAL STABILIZER",
    category: "cameras",
    categoryLabel: "Production Gear",
    dailyRate: 100.0,
    securityDeposit: 150,
    image: "/images/gear/catalog/DJI_RS-2-Pro-GIMBAL-STABILIZER.jpg",
    specs: ["Pro Studio Gear"],
    description: "المواصفات الفنية: النوع: جيمبل تثبيت احترافي | الحمولة: كاميرات سينمائية حتى 3kg | المحرك: محركات بمستوى احترافي | البطارية: مدة تشغيل ممتدة من 14 إلى 18 ساع...",
  },
  {
    id: "movmax-movmax-blade-arm-2",
    name: "MOVMAX MOVMAX BLADE ARM",
    category: "cameras",
    categoryLabel: "Production Gear",
    dailyRate: 100.0,
    securityDeposit: 150,
    image: "/images/gear/catalog/MOVMAX_BLADE-ARM.jpg",
    specs: ["Pro Studio Gear"],
    description: "المواصفات الفنية: النوع: ذراع تثبيت احترافي | الهيكل: خفيف الوزن وصلب | التركيب: متوافق مع قضبان 15mm | قدرة التحمل: تجهيزات التصوير السينمائي الاحترافية | ا...",
  },
  {
    id: "ulanzi-section-cup-sc-02-2",
    name: "ULANZI SECTION CUP SC 02",
    category: "cameras",
    categoryLabel: "Production Gear",
    dailyRate: 20.0,
    securityDeposit: 30,
    image: "/images/gear/catalog/ULANZI_SECTION-CUP-SC-02.jpg",
    specs: ["Pro Studio Gear"],
    description: "المواصفات الفنية: النوع: كوب تثبيت للهاتف مع حامل | التوافق: تركيب عام لجميع الهواتف | مقاس الهاتف: يدعم حتى 6.5 بوصة | الحامل: متوافق مع قضبان 15mm | القفل:...",
  },
  {
    id: "neewer-dl400-electric-motorized-video-dolly-2",
    name: "NEEWER DL400 ELECTRIC MOTORIZED VIDEO DOLLY",
    category: "cameras",
    categoryLabel: "Production Gear",
    dailyRate: 350.0,
    securityDeposit: 525,
    image: "/images/gear/catalog/NEEWER_DL400-ELECTRIC-MOTORIZED-VIDEO-DOLLYSECTION-CUP-SC-02.jpg",
    specs: ["Pro Studio Gear"],
    description: "المواصفات الفنية: النوع: نظام دولي كهربائي بمحرك | المحرك: محرك DC احترافي | المسار: نظام مسار قابل للتمديد | التحكم في السرعة: ضبط متغير للسرعة | الملحقات: ...",
  },
  {
    id: "tilta-tss-01-professional-cinema-slider-system-2",
    name: "TILTA TSS-01 Professional Cinema Slider System",
    category: "cameras",
    categoryLabel: "Production Gear",
    dailyRate: 300.0,
    securityDeposit: 450,
    image: "/images/gear/catalog/TILTA_TSS-01-Professional-Cinema-Slider-System.jpg",
    specs: ["Pro Studio Gear"],
    description: "المواصفات الفنية: النوع: سلايدر سينمائي بمحرك | قدرة التحمل: 10kg | مسافة الحركة: من 100 إلى 120cm | الطاقة: يعمل بالبطارية | التحكم: قرص لضبط السرعة | الترك...",
  },
  {
    id: "hollyland-mars-400-s-pro-2",
    name: "HOLLYLAND MARS 400 S PRO",
    category: "cameras",
    categoryLabel: "Production Gear",
    dailyRate: 95.0,
    securityDeposit: 142,
    image: "/images/gear/catalog/HOLLYLAND_MARS-400-S-PRO.jpg",
    specs: ["Pro Studio Gear"],
    description: "المواصفات الفنية: النوع: إرسال فيديو لاسلكي | الدقة: 1080p HD | المدى: حتى 400 قدم (120 مترًا) | زمن التأخير: أقل من 150ms (منخفض جدًا) | التردد: 5.8GHz رقمي...",
  },
  {
    id: "qkens-4k-transmitter-system-2",
    name: "QKENS 4K TRANSMITTER SYSTEM",
    category: "cameras",
    categoryLabel: "Production Gear",
    dailyRate: 350.0,
    securityDeposit: 525,
    image: "/images/gear/arri-alexa-mini-lf.jpg",
    specs: ["Pro Studio Gear"],
    description: "المواصفات الفنية: النوع: إرسال لاسلكي احترافي بدقة 4K | الدقة: 4K (3840x2160) عند 30fps | المدى: أكثر من 500 قدم (أكثر من 150 مترًا) | التردد: متعدد القنوات ...",
  },
  {
    id: "swit-4k-monitor-7-inch-cm-s75c-2",
    name: "SWIT 4K MONITOR 7 INCH CM-S75C",
    category: "cameras",
    categoryLabel: "Production Gear",
    dailyRate: 350.0,
    securityDeposit: 525,
    image: "/images/gear/catalog/SWIT_4K-MONITOR-7-INCH-CM-S75C.jpg",
    specs: ["Pro Studio Gear"],
    description: "المواصفات الفنية: حجم الشاشة: IPS LCD مقاس 7 بوصة | الدقة: 4K (3840x2160) عند 60fps | عمق الألوان: 10-bit | السطوع: 1500 nits كحد أقصى | التباين: 1200:1 | مد...",
  },
  {
    id: "seetec-4k-monitor-19-inch-2",
    name: "SEETEC 4K MONITOR 19 INCH",
    category: "cameras",
    categoryLabel: "Production Gear",
    dailyRate: 350.0,
    securityDeposit: 525,
    image: "/images/gear/catalog/SEETEC_4K-MONITOR-19-INCH.jpg",
    specs: ["Pro Studio Gear"],
    description: "المواصفات الفنية: حجم الشاشة: LCD مقاس 19 بوصة | الدقة: 4K (3840x2160) | السطوع: من 800 إلى 1000 nits | فضاء الألوان: RGB + YUV | مداخل الفيديو: عدة مداخل HD...",
  },
  {
    id: "black-magic-atem-mini-pro-4-channels-fhd-2",
    name: "BLACK MAGIC ATEM MINI PRO 4 CHANNELS FHD",
    category: "cameras",
    categoryLabel: "Production Gear",
    dailyRate: 150.0,
    securityDeposit: 225,
    image: "/images/gear/catalog/BLACK-MAGIC_ATEM-MINI-PRO-4-CHANNELS-FHD.jpg",
    specs: ["Pro Studio Gear"],
    description: "المواصفات الفنية: النوع: ميكسر فيديو للبث المباشر | قنوات الإدخال: 4x HDMI | الصيغة: Full HD (1920x1080) عند 60fps | الانتقالات: 16 نمطًا احترافيًا | DVE: تغ...",
  },
  {
    id: "feel-world-mobile-teleprompter-2",
    name: "FEEL WORLD MOBILE TELEPROMPTER",
    category: "cameras",
    categoryLabel: "Production Gear",
    dailyRate: 350.0,
    securityDeposit: 525,
    image: "/images/gear/catalog/FEEL-WORLD_MOBILE-TELEPROMPTER.jpg",
    specs: ["Pro Studio Gear"],
    description: "المواصفات الفنية: النوع: تيليبرومبتر محمول للأجهزة الذكية | التوافق: الهواتف الذكية والأجهزة اللوحية (حتى 10 بوصة) | العرض: يدعم تمرير النص | الزجاج العاكس: ...",
  },
  {
    id: "desview-t22-professional-teleprompter-2",
    name: "DESVIEW T22 PROFESSIONAL TELEPROMPTER",
    category: "cameras",
    categoryLabel: "Production Gear",
    dailyRate: 350.0,
    securityDeposit: 525,
    image: "/images/gear/catalog/DESVIEW_T22-PROFESSIONAL-TELEPROMPTER.jpg",
    specs: ["Pro Studio Gear"],
    description: "المواصفات الفنية: النوع: تيليبرومبتر احترافي للاستوديو والتصوير الخارجي | حجم الشاشة: 22 بوصة | الزجاج العاكس: Beam Splitter احترافي | زاوية الرؤية: 45 درجة ...",
  },
  {
    id: "crony-cn01-power-station-800w-2",
    name: "CRONY CN01 POWER STATION 800W",
    category: "cameras",
    categoryLabel: "Production Gear",
    dailyRate: 350.0,
    securityDeposit: 525,
    image: "/images/gear/catalog/CRONY_CN01-POWER-STATION-800W.jpg",
    specs: ["Pro Studio Gear"],
    description: "المواصفات الفنية: النوع: محطة طاقة محمولة | قدرة الخرج: 800W متواصلة، 1600W كحد أقصى | البطارية: ليثيوم أيون | المخارج: 2x AC (110-240V)، و4x USB، و1x 12V DC...",
  },
  {
    id: "fogger-a-2000-fogger-2",
    name: "FOGGER A-2000 FOGGER",
    category: "cameras",
    categoryLabel: "Production Gear",
    dailyRate: 350.0,
    securityDeposit: 525,
    image: "/images/gear/catalog/FOGGER_A-2000.jpg",
    specs: ["Pro Studio Gear"],
    description: "المواصفات الفنية: النوع: ماكينة ضباب/دخان | الخرج: أكثر من 2000 CFM | زمن التسخين: من 3 إلى 5 دقائق | كثافة الضباب: قابلة للضبط | نوع السائل: زيتي (سعة من 1 ...",
  },
  {
    id: "ewinner-filter-ring-adapter-2",
    name: "eWINNER FILTER RING ADAPTER",
    category: "lenses",
    categoryLabel: "Cinema Lens",
    dailyRate: 180.0,
    securityDeposit: 270,
    image: "/images/gear/catalog/eWINNER_FILTER-RING-ADAPTER.jpg",
    specs: ["Pro Studio Gear"],
    description: "المواصفات الفنية: النوع: طقم حلقات تحويل للفلاتر | المقاسات: 37 و49 و52 و55 و58 و62 و67 و72 و77 و82mm | الخامة: سبيكة ألومنيوم | الغرض: التحويل بين مقاسات ال...",
  },
  {
    id: "amaran-300-c-2",
    name: "Amaran 300 C",
    category: "lighting",
    categoryLabel: "Studio Light",
    dailyRate: 190.0,
    securityDeposit: 285,
    image: "/images/gear/catalog/Amaran_300C.jpg",
    specs: ["Pro Studio Gear"],
    description: "المواصفات الفنية: النوع: إضاءة LED احترافية | القدرة: ما يعادل 300W | اللون: ثنائي اللون (قابل للضبط من 3200K إلى 5600K) | CRI: أكثر من 95 لدقة الألوان | الت...",
  },
  {
    id: "amaran-se-spot-light-2",
    name: "Amaran SE Spot Light",
    category: "lighting",
    categoryLabel: "Studio Light",
    dailyRate: 120.0,
    securityDeposit: 180,
    image: "/images/gear/catalog/Amaran_SE-Spot-Light.jpg",
    specs: ["Pro Studio Gear"],
    description: "المواصفات الفنية: النوع: إضاءة سبوت LED احترافية | القدرة: سبوت عالي الشدة | اللون: درجة حرارة لون قابلة للضبط | CRI: أكثر من 98 بدقة احترافية | التعتيم: سلس...",
  },
  {
    id: "godox-sl150-2",
    name: "GODOX SL150",
    category: "lighting",
    categoryLabel: "Studio Light",
    dailyRate: 120.0,
    securityDeposit: 180,
    image: "/images/gear/catalog/GODOX_SL150.jpg",
    specs: ["Pro Studio Gear"],
    description: "المواصفات الفنية: النوع: إضاءة HMI احترافية | القدرة: ما يعادل 150W | قاعدة Bowens: تركيب سينمائي قياسي | اللون: متوازن مع ضوء النهار | الطاقة: تعمل بتيار AC",
  },
  {
    id: "godox-ad-600-pro-2",
    name: "GODOX AD 600 PRO",
    category: "lighting",
    categoryLabel: "Studio Light",
    dailyRate: 400.0,
    securityDeposit: 600,
    image: "/images/gear/catalog/GODOX_AD-600-PRO.jpg",
    specs: ["Pro Studio Gear"],
    description: "المواصفات الفنية: النوع: فلاش احترافي | القدرة: 600Ws | زمن إعادة الشحن: سريع من 0.01 إلى 2.5 ثانية | التكرار: حتى 150 فلاش في الثانية | التصنيع: احترافي مقا...",
  },
  {
    id: "aputurenova-p-300-c-2",
    name: "APUTURENOVA P 300 C",
    category: "lighting",
    categoryLabel: "Studio Light",
    dailyRate: 230.0,
    securityDeposit: 345,
    image: "/images/gear/catalog/APUTURE_NOVA-P-300-C.jpg",
    specs: ["Pro Studio Gear"],
    description: "المواصفات الفنية: النوع: لوح إضاءة LED احترافي | القدرة: ما يعادل 300W | الإضاءة: ضوء نهار بطيف كامل | دقة الألوان: CRI عالٍ | الملحقات: حقيبة صلبة، وحدة تحك...",
  },
  {
    id: "nanlight-rgb-5c-2",
    name: "NANLIGHT RGB 5C",
    category: "lighting",
    categoryLabel: "Studio Light",
    dailyRate: 120.0,
    securityDeposit: 180,
    image: "/images/gear/catalog/NANLIGHT_RGB-5C.jpg",
    specs: ["Pro Studio Gear"],
    description: "المواصفات الفنية: النوع: إضاءة ملونة RGB | اللون: RGB بطيف كامل | الحجم: 5 بوصة | التعتيم: نطاق كامل | الطاقة: تعمل بـ AC/DC | التصنيع: احترافي ومحمول",
  },
  {
    id: "godox-v1s-flash-light-2",
    name: "GODOX V1S FLASH LIGHT",
    category: "lighting",
    categoryLabel: "Studio Light",
    dailyRate: 120.0,
    securityDeposit: 180,
    image: "/images/gear/catalog/GODOX_V1S-FLASH-LIGHT.jpg",
    specs: ["Pro Studio Gear"],
    description: "المواصفات الفنية: النوع: فلاش كاميرا احترافي | القدرة: فلاش عالي الخرج | إعادة الشحن: سريع من 0.01 إلى 2.6 ثانية | التكرار: حتى 40 فلاش في الثانية | التصنيع:...",
  },
  {
    id: "godox-x2ts-flash-trigger-2",
    name: "GODOX X2TS FLASH TRIGGER",
    category: "lighting",
    categoryLabel: "Studio Light",
    dailyRate: 120.0,
    securityDeposit: 180,
    image: "/images/gear/catalog/GODOX_V1S-FLASH-LIGHT-2.jpg",
    specs: ["Pro Studio Gear"],
    description: "المواصفات الفنية: النوع: مُشغّل فلاش لاسلكي (Trigger) | التردد: 2.4GHz رقمي | المدى: مسافة احترافية | القنوات: يدعم عدة قنوات | التوافق: أنظمة فلاش GODOX | ا...",
  },
  {
    id: "godox-xpros-flash-trigger-2",
    name: "GODOX XPROS FLASH TRIGGER",
    category: "lighting",
    categoryLabel: "Studio Light",
    dailyRate: 120.0,
    securityDeposit: 180,
    image: "/images/gear/aputure-600c-pro.jpg",
    specs: ["Pro Studio Gear"],
    description: "المواصفات الفنية: النوع: مُشغّل فلاش احترافي (Trigger) | التردد: 2.4GHz لاسلكي رقمي | القنوات: يدعم عدة قنوات | التوافق: أنظمة الفلاش الاحترافية | المدى: مسا...",
  },
  {
    id: "ulanzi-rgb-l-light-2",
    name: "ULANZI RGB L LIGHT",
    category: "lighting",
    categoryLabel: "Studio Light",
    dailyRate: 120.0,
    securityDeposit: 180,
    image: "/images/gear/catalog/ULANZI_RGB-I-LIGHT.jpg",
    specs: ["Pro Studio Gear"],
    description: "المواصفات الفنية: النوع: إضاءة ملونة RGB | اللون: RGB بطيف كامل | الحجم: مقاس L مدمج | التعتيم: تحكم كامل | الطاقة: بطارية محمولة | التصنيع: خفيف ومحمول | ال...",
  },
  {
    id: "yongnuo-yn600l-ii-2",
    name: "YONGNUO YN600L II",
    category: "cameras",
    categoryLabel: "Production Gear",
    dailyRate: 350.0,
    securityDeposit: 525,
    image: "/images/gear/catalog/YONGNUO_YN600L-II-2-1.jpg",
    specs: ["Pro Studio Gear"],
    description: "المواصفات الفنية: النوع: إضاءة LED احترافية | القدرة: ما يعادل 600W | اللون: متوازن مع ضوء النهار | CRI: أكثر من 95 لدقة الألوان | التعتيم: شدة متغيرة | التص...",
  },
  {
    id: "yongnuo-yn300-iii-2",
    name: "YONGNUO YN300 III",
    category: "cameras",
    categoryLabel: "Production Gear",
    dailyRate: 350.0,
    securityDeposit: 525,
    image: "/images/gear/catalog/YONGNUO_YN600L-II-2.jpg",
    specs: ["Pro Studio Gear"],
    description: "المواصفات الفنية: النوع: إضاءة LED احترافية | القدرة: ما يعادل 300W | اللون: متوازن مع ضوء النهار | CRI: دقة ألوان عالية | التعتيم: شدة متغيرة | التصنيع: هيك...",
  },
  {
    id: "nanlight-evox-1200-combo-2",
    name: "NANLIGHT EVOX 1200 COMBO",
    category: "lighting",
    categoryLabel: "Studio Light",
    dailyRate: 120.0,
    securityDeposit: 180,
    image: "/images/gear/catalog/NANLUX_EVOK-1200-COMBO.jpg",
    specs: ["Pro Studio Gear"],
    description: "المواصفات الفنية: النوع: طقم إضاءة سينمائية احترافي | القدرة: ما يعادل 1200W | الملحقات: أبواب تحكم (Barndoors)، حامل إضاءة، طقم كامل | التصنيع: بمستوى سينما...",
  },
  {
    id: "nanlight-pavotube-ii-30xr-4kit-rgbww-tubelight-2",
    name: "Nanlight Pavotube II 30XR 4Kit RGBWW Tubelight",
    category: "lighting",
    categoryLabel: "Studio Light",
    dailyRate: 70.0,
    securityDeposit: 105,
    image: "/images/gear/catalog/Nanlight_Pavotube-II-30XR-4Kit-RGBWW.jpg",
    specs: ["Pro Studio Gear"],
    description: "المواصفات الفنية: النوع: نظام إضاءة أنبوبية RGBWW | الحجم: أنابيب 30XR | اللون: RGBWW بطيف كامل | الطاقة: محوّل 15V/4A لكل وحدة | الكابلات: 9.8 قدم (3 أمتار)...",
  },
  {
    id: "godox-sa-17-gobo-kit-sa-p-sa-06-sa-05-2",
    name: "Godox SA-17 GOBO Kit / SA-P / SA-06 / SA-05",
    category: "bundles",
    categoryLabel: "Turnkey Kit",
    dailyRate: 300.0,
    securityDeposit: 450,
    image: "/images/gear/catalog/Godox_SA-17-GOBO-Kit-1.jpg",
    specs: ["Pro Studio Gear"],
    isKit: true,
    includedInKit: ["Godox SA-17 Bowens Mount Adapter", "SA-P Projection Attachment with 85mm Lens", "SA-06 Iris Diaphragm", "SA-05 Scrim Set", "16-piece GOBO Architectural Pattern Set", "Framing Shutter Blades"],
    description: "المواصفات الفنية: النوع: نظام ملحق GOBO للإضاءة السبوت | المكونات: عدة عدسات إسقاط وقواعد تركيب | الملحقات: 11 قطعة إضافية بالطقم | القاعدة: تركيب سينمائي اح...",
  },
  {
    id: "tg-bl-106-pm30-tg-2",
    name: "TG BL-106-PM30-TG",
    category: "cameras",
    categoryLabel: "Production Gear",
    dailyRate: 350.0,
    securityDeposit: 525,
    image: "/images/gear/arri-alexa-mini-lf.jpg",
    specs: ["Pro Studio Gear"],
    description: "المواصفات الفنية: النوع: نظام إضاءة احترافي | التركيب: تركيب احترافي | التصنيع: جودة احترافية | المميزات: طقم كامل من وحدتين | المواصفة: نظام إضاءة متكامل",
  },
  {
    id: "nicefoto-65cm-lantern-softbox-2",
    name: "Nicefoto 65cm Lantern Softbox",
    category: "lighting",
    categoryLabel: "Studio Light",
    dailyRate: 60.0,
    securityDeposit: 90,
    image: "/images/gear/catalog/Nicefoto_65cm-Lantern-Softbox.jpg",
    specs: ["Pro Studio Gear"],
    description: "المواصفات الفنية: النوع: سوفت بوكس على شكل فانوس | المقاس: قطر 65cm | القاعدة: Bowens احترافية | التصنيع: معدِّل إضاءة احترافي | المميزات: إضاءة ناعمة ومتجانسة",
  },
  {
    id: "phottix-raja-105cm-2",
    name: "Phottix Raja 105cm",
    category: "cameras",
    categoryLabel: "Production Gear",
    dailyRate: 60.0,
    securityDeposit: 90,
    image: "/images/gear/catalog/Phottix_Raja-150cm-2.jpg",
    specs: ["Pro Studio Gear"],
    description: "المواصفات الفنية: النوع: معدِّل إضاءة أوكتابوكس | المقاس: قطر 105cm | القاعدة: Bowens احترافية | التصنيع: تحكم احترافي في الإضاءة | المميزات: تحكم في الاتجاه...",
  },
  {
    id: "nanlite-square-60cm-x-90-cm-2",
    name: "Nanlite Square 60cm X 90 cm",
    category: "lighting",
    categoryLabel: "Studio Light",
    dailyRate: 120.0,
    securityDeposit: 180,
    image: "/images/gear/catalog/Nanlite_Square-60cm-X-90cm.jpg",
    specs: ["Pro Studio Gear"],
    description: "المواصفات الفنية: النوع: سوفت بوكس مستطيل | الأبعاد: 60cm x 90cm | الملحقات: وحدتان مع ناشرات ضوء وشبكات وحقائب | التركيب: تركيب احترافي | التصنيع: تحكم احتر...",
  },
  {
    id: "godox-strip-30cm-x-120cm-2",
    name: "Godox Strip 30cm x 120CM",
    category: "lighting",
    categoryLabel: "Studio Light",
    dailyRate: 120.0,
    securityDeposit: 180,
    image: "/images/gear/catalog/Godox_Strip-30cm-x-120cm.jpg",
    specs: ["Pro Studio Gear"],
    description: "المواصفات الفنية: النوع: معدِّل إضاءة شريطي (Strip) | الأبعاد: 30cm x 120cm | الملحقات: ناشرات ضوء، شبكات، حقائب حمل | القاعدة: Bowens احترافية | التصنيع: تح...",
  },
  {
    id: "manfrotto-80-cm-sini-reflector-2",
    name: "Manfrotto 80 CM Sini Reflector",
    category: "lighting",
    categoryLabel: "Studio Light",
    dailyRate: 120.0,
    securityDeposit: 180,
    image: "/images/gear/aputure-600c-pro.jpg",
    specs: ["Pro Studio Gear"],
    description: "المواصفات الفنية: النوع: عاكس ضوء احترافي | المقاس: قطر 80 سنتيمترًا | نوع العاكس: متعدد الأسطح (تصميم موجي) | التصنيع: هيكل احترافي | المميزات: نظام عاكس مت...",
  },
  {
    id: "godox-100cm-x-150-cm-sini-reflector-2",
    name: "Godox 100cm X 150 CM Sini Reflector",
    category: "lighting",
    categoryLabel: "Studio Light",
    dailyRate: 120.0,
    securityDeposit: 180,
    image: "/images/gear/catalog/Godox_Strip-30cm-x-120cm-2.jpg",
    specs: ["Pro Studio Gear"],
    description: "المواصفات الفنية: النوع: عاكس ضوء احترافي | الأبعاد: 100cm x 150cm | نوع العاكس: تصميم موجي | التركيب: قطع تركيب احترافية | التصنيع: سطح عاكس احترافي | الممي...",
  },
  {
    id: "ezy-view-director-tent-2",
    name: "Ezy View Director tent",
    category: "cameras",
    categoryLabel: "Production Gear",
    dailyRate: 350.0,
    securityDeposit: 525,
    image: "/images/gear/arri-alexa-mini-lf.jpg",
    specs: ["Pro Studio Gear"],
    description: "المواصفات الفنية: النوع: خيمة مراقبة للمخرج | الغرض: حماية منطقة المراقبة (Video Village) | الخامة: قماش شديد التحمل | المقاس: خيمة بالحجم الكامل | المميزات:...",
  },
  {
    id: "promage-green-chroma-3x5-meter-2",
    name: "promage Green Chroma 3X5 Meter",
    category: "cameras",
    categoryLabel: "Production Gear",
    dailyRate: 150.0,
    securityDeposit: 225,
    image: "/images/gear/catalog/promage_Green-Chroma-3X5-Meter.jpg",
    specs: ["Pro Studio Gear"],
    description: "المواصفات الفنية: النوع: خلفية كروما خضراء | الأبعاد: 3 أمتار x 5 أمتار | اللون: أخضر احترافي | الخامة: قماش | التركيب: نظام إطار محمول | التصنيع: بمستوى احت...",
  },
  {
    id: "promage-white-3x5-meter-2",
    name: "promage White 3X5 Meter",
    category: "cameras",
    categoryLabel: "Production Gear",
    dailyRate: 150.0,
    securityDeposit: 225,
    image: "/images/gear/catalog/promage_White-3X5-Meter.jpg",
    specs: ["Pro Studio Gear"],
    description: "المواصفات الفنية: النوع: خلفية بيضاء | الأبعاد: 3 أمتار x 5 أمتار | اللون: أبيض احترافي | الخامة: قماش | التركيب: نظام إطار محمول | التصنيع: بمستوى احترافي |...",
  },
  {
    id: "savage-seamless-background-paper-2-7-x-10-8-meter-2",
    name: "Savage Seamless Background Paper 2.7 x 10.8 meter",
    category: "cameras",
    categoryLabel: "Production Gear",
    dailyRate: 40.0,
    securityDeposit: 60,
    image: "/images/gear/catalog/Savage_Seamless-Background-Paper-2.7-x-10.8-meter.jpg",
    specs: ["Pro Studio Gear"],
    description: "المواصفات الفنية: النوع: خلفية ورقية بدون فواصل (Seamless) | الأبعاد: لفات مقاس 2.7m x 10.8m | الألوان: 10 خيارات (أسود، رمادي، أخضر، بني، أصفر، أزرق، برتقال...",
  },
  {
    id: "baofeng-uv-5r-walkie-talkies-2",
    name: "BAOFENG UV-5R Walkie Talkies",
    category: "cameras",
    categoryLabel: "Production Gear",
    dailyRate: 200.0,
    securityDeposit: 300,
    image: "/images/gear/catalog/BAOFENG_UV-5R-Walkie-Talkie.jpg",
    specs: ["Pro Studio Gear"],
    description: "المواصفات الفنية: النوع: جهاز لاسلكي (ووكي توكي) احترافي | التردد: نطاق UHF/VHF | المدى: اتصال لمسافات احترافية | الطاقة: بطارية قابلة للشحن | التصنيع: احترا...",
  },
  {
    id: "baoyuan-17by379l-walkie-talkies-2",
    name: "BAOYUAN 17BY379L Walkie Talkies",
    category: "cameras",
    categoryLabel: "Production Gear",
    dailyRate: 200.0,
    securityDeposit: 300,
    image: "/images/gear/arri-alexa-mini-lf.jpg",
    specs: ["Pro Studio Gear"],
    description: "المواصفات الفنية: النوع: جهاز لاسلكي (ووكي توكي) احترافي | المدى: مسافة اتصال احترافية | الطاقة: نظام بطارية قابلة للشحن | التصنيع: بمستوى احترافي | المميزات...",
  },
  {
    id: "zoom-h6-sound-mixer-2",
    name: "ZOOM H6 Sound Mixer",
    category: "audio",
    categoryLabel: "Pro Audio",
    dailyRate: 45.0,
    securityDeposit: 68,
    image: "/images/gear/catalog/ZOOM_H6-SOUND-MIXER.jpg",
    specs: ["Pro Studio Gear"],
    description: "المواصفات الفنية: النوع: ميكسر صوت محمول 6 قنوات | المداخل: 2x مدخل مشترك XLR/3.5mm | صيغ التسجيل: WAV وMP3 | عمق البت: 16/24-bit | معدل العينة: 44.1/48kHz |...",
  },
  {
    id: "zoom-h8-sound-mixer-2",
    name: "ZOOM H8 Sound Mixer",
    category: "audio",
    categoryLabel: "Pro Audio",
    dailyRate: 95.0,
    securityDeposit: 142,
    image: "/images/gear/sennheiser-mkh416-kit.jpg",
    specs: ["Pro Studio Gear"],
    description: "المواصفات الفنية: النوع: ميكسر صوت محمول 8 قنوات | المداخل: 2x مدخل مشترك XLR/3.5mm | صيغ التسجيل: WAV وMP3 | عمق البت: 16/24-bit | معدل العينة: 44.1/48kHz |...",
  },
  {
    id: "behringer-ha400-sound-4-channel-amplifier-2",
    name: "BEHRINGER HA400 Sound 4 Channel Amplifier",
    category: "cameras",
    categoryLabel: "Production Gear",
    dailyRate: 350.0,
    securityDeposit: 525,
    image: "/images/gear/catalog/BEHRINGER_HA400-SOUND-4-CHANNEL-AMPLIFIER.jpg",
    specs: ["Pro Studio Gear"],
    description: "المواصفات الفنية: النوع: مضخّم سماعات 4 قنوات | المداخل: 1x مدخل صوت ستيريو | المخارج: 4x مخارج سماعات ستيريو مستقلة | الطاقة: USB أو بطاريات AA | التحكم في ...",
  },
  {
    id: "generic-live-sound-card-voice-changer-2",
    name: "Generic Live Sound Card Voice Changer",
    category: "cameras",
    categoryLabel: "Production Gear",
    dailyRate: 350.0,
    securityDeposit: 525,
    image: "/images/gear/catalog/GENERIC_LIVE-SOUND-CARD-VOICE-CHANGER.jpg",
    specs: ["Pro Studio Gear"],
    description: "المواصفات الفنية: النوع: كارت صوت للبث المباشر مع مؤثرات | المداخل: عدة مداخل صوت | المخارج: مخرج صوت + مخرج سماعات | المؤثرات: تغيير الصوت، صدى، تردد (Rever...",
  },
  {
    id: "saramonic-witalk-9-wireless-headset-intercom-system-2",
    name: "SARAMONIC WiTalk 9 Wireless Headset Intercom System",
    category: "cameras",
    categoryLabel: "Production Gear",
    dailyRate: 350.0,
    securityDeposit: 525,
    image: "/images/gear/catalog/SARAMONIC_WiTalk-9-Wireless-Headset-Intercom-System.jpg",
    specs: ["Pro Studio Gear"],
    description: "المواصفات الفنية: النوع: نظام إنتركم لاسلكي احترافي | المستخدمون: نظام لـ 5 أشخاص | التردد: 1.9GHz | الاتصال: Full-duplex (اتصال ثنائي الاتجاه في نفس الوقت) ...",
  },
  {
    id: "sony-utx-b03-transmitter-mic-2",
    name: "Sony UTX-B03 Transmitter Mic",
    category: "audio",
    categoryLabel: "Pro Audio",
    dailyRate: 95.0,
    securityDeposit: 142,
    image: "/images/gear/catalog/Sony_UTX-B03-TRANSMITTER-MIC.jpg",
    specs: ["Pro Studio Gear"],
    description: "المواصفات الفنية: النوع: ميكروفون لاسلكي بجهاز إرسال | التردد: نطاق UHF احترافي | المدى اللاسلكي: أكثر من 100 متر | الميكروفون: لافالير يُثبّت على الرقبة/الم...",
  },
  {
    id: "sony-urx-p03-receiver-mic-2",
    name: "Sony URX-P03 Receiver Mic",
    category: "audio",
    categoryLabel: "Pro Audio",
    dailyRate: 95.0,
    securityDeposit: 142,
    image: "/images/gear/catalog/URX-P03-RECEIVER-MIC.jpg",
    specs: ["Pro Studio Gear"],
    description: "المواصفات الفنية: النوع: جهاز استقبال لاسلكي لجهاز الإرسال | التردد: نطاق UHF احترافي | القنوات: متوافق مع أجهزة إرسال Sony | الخرج: XLR احترافي + محوّل 3.5m...",
  },
  {
    id: "hollyland-lark-m2-2",
    name: "HOLLYLAND LARK M2",
    category: "cameras",
    categoryLabel: "Production Gear",
    dailyRate: 150.0,
    securityDeposit: 225,
    image: "/images/gear/catalog/HOLLYLAND_LARK-M2.jpg",
    specs: ["Pro Studio Gear"],
    description: "المواصفات الفنية: النوع: نظام ميكروفون لافالير لاسلكي | التكوين: 2 ميكروفون إرسال + 1 جهاز استقبال | المدى: أكثر من 100 متر لاسلكي | زمن التأخير: أقل من 150m...",
  },
  {
    id: "dji-mic-2-2",
    name: "DJI MIC 2",
    category: "audio",
    categoryLabel: "Pro Audio",
    dailyRate: 120.0,
    securityDeposit: 180,
    image: "/images/gear/catalog/DJI-MIC-1.jpg",
    specs: ["Pro Studio Gear"],
    description: "المواصفات الفنية: النوع: نظام ميكروفون لافالير لاسلكي | التكوين: 2 ميكروفون إرسال + 1 جهاز استقبال | المدى: أكثر من 250 مترًا لاسلكي (في المساحات المفتوحة) |...",
  },
  {
    id: "dji-mic-1-2",
    name: "DJI MIC 1",
    category: "audio",
    categoryLabel: "Pro Audio",
    dailyRate: 120.0,
    securityDeposit: 180,
    image: "/images/gear/catalog/DJI-MIC-2.jpg",
    specs: ["Pro Studio Gear"],
    description: "المواصفات الفنية: النوع: نظام ميكروفون لافالير لاسلكي | التكوين: 2 ميكروفون إرسال + 1 جهاز استقبال | المدى: أكثر من 250 مترًا لاسلكي | زمن التأخير: أقل من 15...",
  },
  {
    id: "godox-wh-m1-hand-mic-2",
    name: "GODOX WH-M1 Hand Mic",
    category: "audio",
    categoryLabel: "Pro Audio",
    dailyRate: 95.0,
    securityDeposit: 142,
    image: "/images/gear/catalog/GODOX_WH-M1-HAND-MIC.jpg",
    specs: ["Pro Studio Gear"],
    description: "المواصفات الفنية: النوع: ميكروفون يدوي لاسلكي | التردد: متوافق مع UHF اللاسلكي | الميكروفون: كبسولة ديناميكية Cardioid | الموصل: خرج XLR احترافي | التصنيع: ه...",
  },
  {
    id: "godox-rx1-receiver-2",
    name: "GODOX RX1 Receiver",
    category: "lighting",
    categoryLabel: "Studio Light",
    dailyRate: 120.0,
    securityDeposit: 180,
    image: "/images/gear/catalog/GODOX_RX1-RECEIVER.jpg",
    specs: ["Pro Studio Gear"],
    description: "المواصفات الفنية: النوع: جهاز استقبال لميكروفون لاسلكي | التردد: نطاق UHF | القنوات: جهاز استقبال بقناة واحدة | الخرج: موصل XLR احترافي | الشاشة: مؤشر قوة ال...",
  },
  {
    id: "rode-ntg4-directional-shotgun-mic-2",
    name: "Rode NTG4+ Directional Shotgun Mic",
    category: "audio",
    categoryLabel: "Pro Audio",
    dailyRate: 60.0,
    securityDeposit: 90,
    image: "/images/gear/catalog/RODE_NTG4-DIRECTIONAL-SHOOTGUN-MIC.jpg",
    specs: ["Pro Studio Gear"],
    description: "المواصفات الفنية: النوع: ميكروفون شوتجن Supercardioid | الاستجابة الترددية: 20Hz-20kHz | الاتجاهية: التقاط عالي الاتجاهية | التركيب: قاعدة ميكروفون قياسية | ...",
  },
  {
    id: "boya-by-ws1000-boom-mic-2",
    name: "Boya BY-WS1000 Boom Mic",
    category: "audio",
    categoryLabel: "Pro Audio",
    dailyRate: 95.0,
    securityDeposit: 142,
    image: "/images/gear/catalog/BOYA_BY-WS1000-BOOM-MIC.jpg",
    specs: ["Pro Studio Gear"],
    description: "المواصفات الفنية: النوع: ميكروفون شوتجن مع حامل بوم | الميكروفون: شوتجن Supercardioid | التعليق: نظام تعليق ماص للصدمات (Shock Mount) | البوم: تركيب على عصا ...",
  },
  {
    id: "sennheiser-mke-200-direct-mic-2",
    name: "Sennheiser MKE 200 Direct Mic",
    category: "audio",
    categoryLabel: "Pro Audio",
    dailyRate: 100.0,
    securityDeposit: 150,
    image: "/images/gear/catalog/SENNHEISER_MKE-200-DIRECT-MIC.jpg",
    specs: ["Pro Studio Gear"],
    description: "المواصفات الفنية: النوع: ميكروفون شوتجن مدمج | الاستجابة الترددية: 50Hz-20kHz | الاتجاهية: Cardioid اتجاهي | التصنيع: تصميم احترافي محمول | الطاقة: Plug-in P...",
  },
  {
    id: "godox-ivm-s1-direct-mic-2",
    name: "Godox IVM-S1 Direct Mic",
    category: "audio",
    categoryLabel: "Pro Audio",
    dailyRate: 95.0,
    securityDeposit: 142,
    image: "/images/gear/catalog/GODOX_IVM-S1-DIRECT-MIC.jpg",
    specs: ["Pro Studio Gear"],
    description: "المواصفات الفنية: النوع: ميكروفون اتجاهي مدمج | الاستجابة الترددية: 50Hz-20kHz | الاتجاهية: Cardioid | الحماية من الرياح: متوافق مع واقي الرياح | الموصل: 3.5...",
  },
  {
    id: "sony-ecm-lv1-stereo-lavalier-mic-2",
    name: "Sony ECM-LV1 Stereo Lavalier Mic",
    category: "audio",
    categoryLabel: "Pro Audio",
    dailyRate: 95.0,
    securityDeposit: 142,
    image: "/images/gear/catalog/SONY_ECM-LV1-STEREO-LAVALIER-MIC.jpg",
    specs: ["Pro Studio Gear"],
    description: "المواصفات الفنية: النوع: ميكروفون لافالير ستيريو | الاستجابة الترددية: 20Hz-20kHz | الستيريو: تسجيل ستيريو حقيقي | الموصل: 3.5mm احترافي | التصنيع: احترافي م...",
  },
  {
    id: "rode-mic-stick-2",
    name: "Rode Mic Stick",
    category: "audio",
    categoryLabel: "Pro Audio",
    dailyRate: 50.0,
    securityDeposit: 75,
    image: "/images/gear/sennheiser-mkh416-kit.jpg",
    specs: ["Pro Studio Gear"],
    description: "المواصفات الفنية: النوع: مسجّل صوت محمول بميكروفون | الميكروفون المدمج: ميكروفون مدمج | التسجيل: تسجيل صوت رقمي | الموصل: خرج 3.5mm | التخزين: ذاكرة قابلة لل...",
  },
  {
    id: "generic-windshield-hand-mic-2",
    name: "Generic Windshield Hand Mic",
    category: "audio",
    categoryLabel: "Pro Audio",
    dailyRate: 95.0,
    securityDeposit: 142,
    image: "/images/gear/catalog/GENERIC_WINDSHIELD-HAND-MIC.jpg",
    specs: ["Pro Studio Gear"],
    description: "المواصفات الفنية: النوع: ميكروفون يدوي مع واقي رياح | الموصل: موصل ميكروفون قياسي | التصنيع: هيكل احترافي | الألوان المتاحة: أسود وأصفر",
  },
  {
    id: "reinhardt-windshield-short-boom-mic-2",
    name: "Reinhardt Windshield Short Boom Mic",
    category: "audio",
    categoryLabel: "Pro Audio",
    dailyRate: 40.0,
    securityDeposit: 60,
    image: "/images/gear/catalog/REINHARDT_WINDSHIELD-SHORT-BOOM-MIC.jpg",
    specs: ["Pro Studio Gear"],
    description: "المواصفات الفنية: النوع: ميكروفون بوم قصير | طول البوم: تصميم بوم مدمج | واقي الرياح: إسفنج احترافي | الميكروفون: Supercardioid اتجاهي | التصنيع: ألومنيوم اح...",
  },
  {
    id: "generic-hand-mic-logo-2",
    name: "Generic Hand Mic Logo",
    category: "audio",
    categoryLabel: "Pro Audio",
    dailyRate: 95.0,
    securityDeposit: 142,
    image: "/images/gear/sennheiser-mkh416-kit.jpg",
    specs: ["Pro Studio Gear"],
    description: "المواصفات الفنية: النوع: ميكروفون يدوي بشعار | الشعار: تخصيص بالعلامة التجارية (مثلث، مربع) | الموصل: ميكروفون قياسي | التصنيع: هيكل احترافي | اللون: خيارات ...",
  },
  {
    id: "rode-vxlr-2",
    name: "Rode VXLR+",
    category: "audio",
    categoryLabel: "Pro Audio",
    dailyRate: 95.0,
    securityDeposit: 142,
    image: "/images/gear/catalog/RODE_VXLR.jpg",
    specs: ["Pro Studio Gear"],
    description: "المواصفات الفنية: النوع: محوّل صوت من XLR إلى 3.5mm | الموصل: من XLR احترافي إلى Mini-jack | المعاوقة: متوافقة مع الصوت الاحترافي | التصنيع: محوّل بهيكل احتر...",
  },
  {
    id: "lemorele-g57-2",
    name: "Lemorele G57",
    category: "cameras",
    categoryLabel: "Production Gear",
    dailyRate: 350.0,
    securityDeposit: 525,
    image: "/images/gear/catalog/LEMORELE_G57.jpg",
    specs: ["Pro Studio Gear"],
    description: "المواصفات الفنية: النوع: نظام ميكروفون لاسلكي | التكوين: 1 جهاز إرسال + 1 جهاز استقبال | التردد: نطاق UHF لاسلكي | المدى: مسافة لاسلكية احترافية | التصنيع: م...",
  },
  {
    id: "boya-by-wm5-2",
    name: "Boya BY-WM5",
    category: "audio",
    categoryLabel: "Pro Audio",
    dailyRate: 95.0,
    securityDeposit: 142,
    image: "/images/gear/catalog/BOYA_BY-WM5.jpg",
    specs: ["Pro Studio Gear"],
    description: "المواصفات الفنية: النوع: نظام ميكروفون لافالير لاسلكي | التكوين: 2 جهاز إرسال + 2 جهاز استقبال | التردد: UHF لاسلكي رقمي | المدى: أكثر من 100 متر لاسلكي | ال...",
  },
  {
    id: "generic-double-earhook-headset-mic-2",
    name: "Generic Double Earhook Headset Mic",
    category: "audio",
    categoryLabel: "Pro Audio",
    dailyRate: 95.0,
    securityDeposit: 142,
    image: "/images/gear/catalog/GENERIC_DOUBLE-EARHOOK-HEADSET-MIC.jpg",
    specs: ["Pro Studio Gear"],
    description: "المواصفات الفنية: النوع: ميكروفون مثبّت على الرأس (Headset) | التثبيت: تصميم بخطافين على الأذنين | الميكروفون: كبسولة على ذراع (Boom) | الموصل: موصل سماعة قي...",
  },
  {
    id: "boya-lavalier-stereo-microphone-by-m1-2",
    name: "Boya Lavalier Stereo Microphone - BY-M1",
    category: "audio",
    categoryLabel: "Pro Audio",
    dailyRate: 95.0,
    securityDeposit: 142,
    image: "/images/gear/catalog/BOYA_Lavalier-Stereo-Microphone-BY-M1.jpg",
    specs: ["Pro Studio Gear"],
    description: "المواصفات الفنية: النوع: ميكروفون لافالير ستيريو | الستيريو: تسجيل ستيريو حقيقي | الاستجابة الترددية: 50Hz-16kHz | الموصل: 3.5mm احترافي | التصنيع: احترافي م...",
  },
];
